// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("AccountMaster", Schema = "dbo")]
    public class AccountMaster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_AccountMaster", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"RollType", Order = 4, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Roll type")]
        public string RollType { get; set; }

        [Column(@"GisLeft", Order = 5, TypeName = "decimal")]
        [Display(Name = "Gis left")]
        public decimal? GisLeft { get; set; }

        [Column(@"GisRight", Order = 6, TypeName = "decimal")]
        [Display(Name = "Gis right")]
        public decimal? GisRight { get; set; }

        [Column(@"BoeYear", Order = 7, TypeName = "decimal")]
        [Display(Name = "Boe year")]
        public decimal? BoeYear { get; set; }

        [Column(@"AcctSegConsFlag", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Acct seg cons flag")]
        public string AcctSegConsFlag { get; set; }

        [Column(@"AcctSpltCodeFlag", Order = 9, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Acct splt code flag")]
        public string AcctSpltCodeFlag { get; set; }

        [Column(@"SrCitizen", Order = 10, TypeName = "decimal")]
        [Display(Name = "Sr citizen")]
        public decimal? SrCitizen { get; set; }

        [Column(@"MultOwnersFlag", Order = 11, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Mult owners flag")]
        public string MultOwnersFlag { get; set; }

        [Column(@"FirePtrlAcres", Order = 12, TypeName = "decimal")]
        [Display(Name = "Fire ptrl acres")]
        public decimal? FirePtrlAcres { get; set; }

        [Column(@"OwnerName", Order = 13, TypeName = "char")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Owner name")]
        public string OwnerName { get; set; }

        [Column(@"CareOfFlag", Order = 14, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Care of flag")]
        public string CareOfFlag { get; set; }

        [Column(@"CareOfName", Order = 15, TypeName = "char")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Care of name")]
        public string CareOfName { get; set; }

        [Column(@"OwnerAdrsNameLine1", Order = 16, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Owner adrs name line 1")]
        public string OwnerAdrsNameLine1 { get; set; }

        [Column(@"OwnerAdrsLine2", Order = 17, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Owner adrs line 2")]
        public string OwnerAdrsLine2 { get; set; }

        [Column(@"OwnerAdrsLine3", Order = 18, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Owner adrs line 3")]
        public string OwnerAdrsLine3 { get; set; }

        [Column(@"OwnrshpPrctImpr", Order = 19, TypeName = "decimal")]
        [Display(Name = "Ownrshp prct impr")]
        public decimal? OwnrshpPrctImpr { get; set; }

        [Column(@"OwnshpPrctLand", Order = 20, TypeName = "decimal")]
        [Display(Name = "Ownshp prct land")]
        public decimal? OwnshpPrctLand { get; set; }

        [Column(@"OwnerAlphaName", Order = 21, TypeName = "char")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Owner alpha name")]
        public string OwnerAlphaName { get; set; }

        [Column(@"Ref", Order = 22, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Ref")]
        public string Ref { get; set; }

        [Column(@"CentroidNumber", Order = 23, TypeName = "char")]
        [MaxLength(21)]
        [StringLength(21)]
        [Display(Name = "Centroid number")]
        public string CentroidNumber { get; set; }

        [Column(@"ParentAcctNumberAcctN", Order = 24, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Parent acct number acct n")]
        public string ParentAcctNumberAcctN { get; set; }

        [Column(@"ZipCode", Order = 25, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Zip code")]
        public string ZipCode { get; set; }

        [Column(@"CodeAreaCode", Order = 26, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Code area code")]
        public string CodeAreaCode { get; set; }

        [Column(@"ZoningCode", Order = 27, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Zoning code")]
        public string ZoningCode { get; set; }

        [Column(@"ValAreaCode", Order = 28, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Val area code")]
        public string ValAreaCode { get; set; }

        [Column(@"PropClassCode", Order = 29, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Prop class code")]
        public string PropClassCode { get; set; }

        [Column(@"LienholderCode", Order = 30, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Lienholder code")]
        public string LienholderCode { get; set; }

        [Column(@"MntnAreaCode", Order = 31, TypeName = "decimal")]
        [Display(Name = "Mntn area code")]
        public decimal? MntnAreaCode { get; set; }

        [Column(@"SegregatedFromAcctAcc", Order = 32, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Segregated from acct acc")]
        public string SegregatedFromAcctAcc { get; set; }

        [Column(@"SitusStrtNmbr", Order = 33, TypeName = "decimal")]
        [Display(Name = "Situs strt nmbr")]
        public decimal? SitusStrtNmbr { get; set; }

        [Column(@"SitusStrtNmbrSufx", Order = 34, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Situs strt nmbr sufx")]
        public string SitusStrtNmbrSufx { get; set; }

        [Column(@"SitusStrtDir", Order = 35, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Situs strt dir")]
        public string SitusStrtDir { get; set; }

        [Column(@"SitusStrtName", Order = 36, TypeName = "char")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Situs strt name")]
        public string SitusStrtName { get; set; }

        [Column(@"SitusStrtNameSufx", Order = 37, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Situs strt name sufx")]
        public string SitusStrtNameSufx { get; set; }

        [Column(@"SitusZipCode", Order = 38, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Situs zip code")]
        public string SitusZipCode { get; set; }

        [Column(@"Twnshp", Order = 39, TypeName = "numeric")]
        [Display(Name = "Twnshp")]
        public decimal? Twnshp { get; set; }

        [Column(@"TwnshpDir", Order = 40, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Twnshp dir")]
        public string TwnshpDir { get; set; }

        [Column(@"Range", Order = 41, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Range")]
        public string Range { get; set; }

        [Column(@"RangDir", Order = 42, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Rang dir")]
        public string RangDir { get; set; }

        [Column(@"Sctn", Order = 43, TypeName = "decimal")]
        [Display(Name = "Sctn")]
        public decimal? Sctn { get; set; }

        [Column(@"QtrSctn", Order = 44, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Qtr sctn")]
        public string QtrSctn { get; set; }

        [Column(@"Prcl", Order = 45, TypeName = "numeric")]
        [Display(Name = "Prcl")]
        public decimal? Prcl { get; set; }

        [Column(@"SpecIntAlph", Order = 46, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Spec int alph")]
        public string SpecIntAlph { get; set; }

        [Column(@"SpecIntNmbr", Order = 47, TypeName = "numeric")]
        [Display(Name = "Spec int nmbr")]
        public decimal? SpecIntNmbr { get; set; }

        [Column(@"CountyNumber", Order = 48, TypeName = "numeric")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }

        [Column(@"HomesteadFlag", Order = 49, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Homestead flag")]
        public string HomesteadFlag { get; set; }

        [Column(@"SbdvnCode", Order = 50, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Sbdvn code")]
        public string SbdvnCode { get; set; }

        [Column(@"LotNmbr", Order = 51, TypeName = "decimal")]
        [Display(Name = "Lot nmbr")]
        public decimal? LotNmbr { get; set; }

        [Column(@"BlckNmbr", Order = 52, TypeName = "decimal")]
        [Display(Name = "Blck nmbr")]
        public decimal? BlckNmbr { get; set; }
    }

}
// </auto-generated>
