// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("AccountSummary", Schema = "dbo")]
    public class AccountSummary
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__AccountS__3214EC270BC6C43E", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Display(Name = "Asmt year")]
        public decimal? AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"AcctLandAssessTotl", Order = 4, TypeName = "decimal")]
        [Display(Name = "Acct land assess totl")]
        public decimal? AcctLandAssessTotl { get; set; }

        [Column(@"AcctImprTotl", Order = 5, TypeName = "decimal")]
        [Display(Name = "Acct impr totl")]
        public decimal? AcctImprTotl { get; set; }

        [Column(@"AcctSpecAses", Order = 6, TypeName = "decimal")]
        [Display(Name = "Acct spec ases")]
        public decimal? AcctSpecAses { get; set; }

        [Column(@"AcctExmpTotal", Order = 7, TypeName = "decimal")]
        [Display(Name = "Acct exmp total")]
        public decimal? AcctExmpTotal { get; set; }

        [Column(@"AcctAcresMkt", Order = 8, TypeName = "decimal")]
        [Display(Name = "Acct acres mkt")]
        public decimal? AcctAcresMkt { get; set; }

        [Column(@"AcctAcresSpc", Order = 9, TypeName = "decimal")]
        [Display(Name = "Acct acres spc")]
        public decimal? AcctAcresSpc { get; set; }

        [Column(@"AcctMobHomeTotl", Order = 10, TypeName = "decimal")]
        [Display(Name = "Acct mob home totl")]
        public decimal? AcctMobHomeTotl { get; set; }

        [Column(@"AcctMrktLandTotl", Order = 11, TypeName = "decimal")]
        [Display(Name = "Acct mrkt land totl")]
        public decimal? AcctMrktLandTotl { get; set; }

        [Column(@"AcctImprMrktValTotl", Order = 12, TypeName = "decimal")]
        [Display(Name = "Acct impr mrkt val totl")]
        public decimal? AcctImprMrktValTotl { get; set; }

        [Column(@"AcctExmpMktTotal", Order = 13, TypeName = "decimal")]
        [Display(Name = "Acct exmp mkt total")]
        public decimal? AcctExmpMktTotal { get; set; }

        [Column(@"UtilUnitAssessVal", Order = 14, TypeName = "decimal")]
        [Display(Name = "Util unit assess val")]
        public decimal? UtilUnitAssessVal { get; set; }

        [Column(@"PpLine1Total", Order = 15, TypeName = "decimal")]
        [Display(Name = "Pp line 1 total")]
        public decimal? PpLine1Total { get; set; }

        [Column(@"UtilOtherAssessVal", Order = 16, TypeName = "decimal")]
        [Display(Name = "Util other assess val")]
        public decimal? UtilOtherAssessVal { get; set; }

        [Column(@"PpLine2Total", Order = 17, TypeName = "decimal")]
        [Display(Name = "Pp line 2 total")]
        public decimal? PpLine2Total { get; set; }

        [Column(@"PpLine3Total", Order = 18, TypeName = "decimal")]
        [Display(Name = "Pp line 3 total")]
        public decimal? PpLine3Total { get; set; }

        [Column(@"PpLine4Total", Order = 19, TypeName = "decimal")]
        [Display(Name = "Pp line 4 total")]
        public decimal? PpLine4Total { get; set; }

        [Column(@"PpLine5Total", Order = 20, TypeName = "decimal")]
        [Display(Name = "Pp line 5 total")]
        public decimal? PpLine5Total { get; set; }

        [Column(@"PpLine6Total", Order = 21, TypeName = "decimal")]
        [Display(Name = "Pp line 6 total")]
        public decimal? PpLine6Total { get; set; }

        [Column(@"MaximumAssessedValue", Order = 22, TypeName = "numeric")]
        [Display(Name = "Maximum assessed value")]
        public decimal? MaximumAssessedValue { get; set; }

        [Column(@"TaxableAssessedValue", Order = 23, TypeName = "numeric")]
        [Display(Name = "Taxable assessed value")]
        public decimal? TaxableAssessedValue { get; set; }

        [Column(@"MaxSpecAssessedValue", Order = 24, TypeName = "numeric")]
        [Display(Name = "Max spec assessed value")]
        public decimal? MaxSpecAssessedValue { get; set; }

        [Column(@"TotalExceptions", Order = 25, TypeName = "numeric")]
        [Display(Name = "Total exceptions")]
        public decimal? TotalExceptions { get; set; }

        [Column(@"Rmv", Order = 26, TypeName = "numeric")]
        [Display(Name = "Rmv")]
        public decimal? Rmv { get; set; }

        [Column(@"Sav", Order = 27, TypeName = "numeric")]
        [Display(Name = "Sav")]
        public decimal? Sav { get; set; }

        [Column(@"MsavLand", Order = 28, TypeName = "numeric")]
        [Display(Name = "Msav land")]
        public decimal? MsavLand { get; set; }

        [Column(@"ExceptionsMav", Order = 29, TypeName = "numeric")]
        [Display(Name = "Exceptions mav")]
        public decimal? ExceptionsMav { get; set; }

        [Column(@"ExceptionsMsav", Order = 30, TypeName = "numeric")]
        [Display(Name = "Exceptions msav")]
        public decimal? ExceptionsMsav { get; set; }

        [Column(@"ExemptionsMav", Order = 31, TypeName = "numeric")]
        [Display(Name = "Exemptions mav")]
        public decimal? ExemptionsMav { get; set; }

        [Column(@"ExemptionsMsav", Order = 32, TypeName = "numeric")]
        [Display(Name = "Exemptions msav")]
        public decimal? ExemptionsMsav { get; set; }

        [Column(@"MsavBaseNsaLand", Order = 33, TypeName = "decimal")]
        [Display(Name = "Msav base nsa land")]
        public decimal? MsavBaseNsaLand { get; set; }

        [Column(@"MsavBaseImprovements", Order = 34, TypeName = "decimal")]
        [Display(Name = "Msav base improvements")]
        public decimal? MsavBaseImprovements { get; set; }

        [Column(@"MsavBaseManuStructure", Order = 35, TypeName = "decimal")]
        [Display(Name = "Msav base manu structure")]
        public decimal? MsavBaseManuStructure { get; set; }

        [Column(@"MsavBaseMkt", Order = 36, TypeName = "numeric")]
        [Display(Name = "Msav base mkt")]
        public decimal? MsavBaseMkt { get; set; }
    }

}
// </auto-generated>
