// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("ChangeFile", Schema = "dbo")]
    public class ChangeFile
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__ChangeFi__3214EC27117F9D94", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"ChngDate", Order = 4, TypeName = "date")]
        [Required]
        [Display(Name = "Chng date")]
        public System.DateTime ChngDate { get; set; }

        [Column(@"ChngTime", Order = 5, TypeName = "decimal")]
        [Required]
        [Display(Name = "Chng time")]
        public decimal ChngTime { get; set; }

        [Column(@"ChngSeq", Order = 6, TypeName = "decimal")]
        [Required]
        [Display(Name = "Chng seq")]
        public decimal ChngSeq { get; set; }

        [Column(@"ChngFldDesc", Order = 7, TypeName = "char")]
        [MaxLength(8)]
        [StringLength(8)]
        [Display(Name = "Chng fld desc")]
        public string ChngFldDesc { get; set; }

        [Column(@"ChngType", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Chng type")]
        public string ChngType { get; set; }

        [Column(@"ChngWsId", Order = 9, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Chng ws ID")]
        public string ChngWsId { get; set; }

        [Column(@"ChngUser", Order = 10, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Chng user")]
        public string ChngUser { get; set; }

        [Column(@"ChngDecPos", Order = 11, TypeName = "decimal")]
        [Display(Name = "Chng dec pos")]
        public decimal? ChngDecPos { get; set; }

        [Column(@"ChngOldValue", Order = 12, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Chng old value")]
        public string ChngOldValue { get; set; }

        [Column(@"ChngNewValue", Order = 13, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Chng new value")]
        public string ChngNewValue { get; set; }

        [Column(@"ChngJvNmbr", Order = 14, TypeName = "decimal")]
        [Display(Name = "Chng jv nmbr")]
        public decimal? ChngJvNmbr { get; set; }
    }

}
// </auto-generated>
