// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("CodeArea", Schema = "dbo")]
    public class CodeArea
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__CodeArea__3214EC271920BF5C", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"CodeArea", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Code area")]
        public string CodeArea_ { get; set; }

        [Column(@"CodeAreaDescription", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Code area description")]
        public string CodeAreaDescription { get; set; }

        [Column(@"CountyNumber", Order = 4, TypeName = "decimal")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }

        [Column(@"AsmtYear", Order = 5, TypeName = "decimal")]
        [Display(Name = "Asmt year")]
        public decimal? AsmtYear { get; set; }

        [Column(@"MaintAreaCode", Order = 6, TypeName = "decimal")]
        [Display(Name = "Maint area code")]
        public decimal? MaintAreaCode { get; set; }

        [Column(@"CodeAreaNumeric", Order = 7, TypeName = "decimal")]
        [Display(Name = "Code area numeric")]
        public decimal? CodeAreaNumeric { get; set; }

        [Column(@"StateCodeArea", Order = 8, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "State code area")]
        public string StateCodeArea { get; set; }
    }

}
// </auto-generated>
