// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("EmployeeMasterComments", Schema = "dbo")]
    public class EmployeeMasterComment
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Employee__3214EC27671F4F74", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"EmployeeNumber", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Employee number")]
        public decimal EmployeeNumber { get; set; }

        [Column(@"EmpMasterCommentDate", Order = 3, TypeName = "date")]
        [Required]
        [Display(Name = "Emp master comment date")]
        public System.DateTime EmpMasterCommentDate { get; set; }

        [Column(@"EmpMasterCommentSeq", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Emp master comment seq")]
        public decimal EmpMasterCommentSeq { get; set; }

        [Column(@"EmpMasterCommentText", Order = 5, TypeName = "char")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Emp master comment text")]
        public string EmpMasterCommentText { get; set; }

        [Column(@"CommentType", Order = 6, TypeName = "char")]
        [Required]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Comment type")]
        public string CommentType { get; set; }
    }

}
// </auto-generated>
