// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("EmployeeYTDAmounts", Schema = "dbo")]
    public class EmployeeYtdAmount
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Employee__3214EC276EC0713C", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"EmployeeNumber", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Employee number")]
        public decimal EmployeeNumber { get; set; }

        [Column(@"PayrollYear", Order = 3, TypeName = "numeric")]
        [Required]
        [Display(Name = "Payroll year")]
        public decimal PayrollYear { get; set; }

        [Column(@"GrossPayYtd", Order = 4, TypeName = "decimal")]
        [Display(Name = "Gross pay ytd")]
        public decimal? GrossPayYtd { get; set; }

        [Column(@"FedTaxPaidYtd", Order = 5, TypeName = "decimal")]
        [Display(Name = "Fed tax paid ytd")]
        public decimal? FedTaxPaidYtd { get; set; }

        [Column(@"StateTaxPaidYtd", Order = 6, TypeName = "decimal")]
        [Display(Name = "State tax paid ytd")]
        public decimal? StateTaxPaidYtd { get; set; }

        [Column(@"FicaPaidYtd", Order = 7, TypeName = "decimal")]
        [Display(Name = "Fica paid ytd")]
        public decimal? FicaPaidYtd { get; set; }

        [Column(@"FicaMedicarePaidYtd", Order = 8, TypeName = "decimal")]
        [Display(Name = "Fica medicare paid ytd")]
        public decimal? FicaMedicarePaidYtd { get; set; }

        [Column(@"FringeGrossYtd", Order = 9, TypeName = "decimal")]
        [Display(Name = "Fringe gross ytd")]
        public decimal? FringeGrossYtd { get; set; }

        [Column(@"DeferGross401KYtd", Order = 10, TypeName = "decimal")]
        [Display(Name = "Defer gross 401 ky td")]
        public decimal? DeferGross401KYtd { get; set; }

        [Column(@"FedStExemptYtd", Order = 11, TypeName = "decimal")]
        [Display(Name = "Fed st exempt ytd")]
        public decimal? FedStExemptYtd { get; set; }

        [Column(@"FedStFicaExemptYtd", Order = 12, TypeName = "decimal")]
        [Display(Name = "Fed st fica exempt ytd")]
        public decimal? FedStFicaExemptYtd { get; set; }

        [Column(@"GrossSubjSutaYtd", Order = 13, TypeName = "decimal")]
        [Display(Name = "Gross subj suta ytd")]
        public decimal? GrossSubjSutaYtd { get; set; }

        [Column(@"AdvancedEicPaymentsYtd", Order = 14, TypeName = "decimal")]
        [Display(Name = "Advanced eic payments ytd")]
        public decimal? AdvancedEicPaymentsYtd { get; set; }

        [Column(@"401KDeductAmountYtd", Order = 15, TypeName = "decimal")]
        [Display(Name = "401 Kd educt amount ytd")]
        public decimal? C401KDeductAmountYtd { get; set; }

        [Column(@"Sect457AmountYtd", Order = 16, TypeName = "decimal")]
        [Display(Name = "Sect 457 amount ytd")]
        public decimal? Sect457AmountYtd { get; set; }
    }

}
// </auto-generated>
