// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("ExemptionMaster", Schema = "dbo")]
    public class ExemptionMaster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Exemptio__3214EC2732AB8735", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"ExemptCode", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Exempt code")]
        public string ExemptCode { get; set; }

        [Column(@"ExmpDesc", Order = 3, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Exmp desc")]
        public string ExmpDesc { get; set; }

        [Column(@"ExmpAmnt", Order = 4, TypeName = "decimal")]
        [Display(Name = "Exmp amnt")]
        public decimal? ExmpAmnt { get; set; }

        [Column(@"AsmtYear", Order = 5, TypeName = "decimal")]
        [Display(Name = "Asmt year")]
        public decimal? AsmtYear { get; set; }

        [Column(@"PropClassCode", Order = 6, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Prop class code")]
        public string PropClassCode { get; set; }

        [Column(@"CountyNumber", Order = 7, TypeName = "numeric")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }
    }

}
// </auto-generated>
