// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("FactorBookMaster", Schema = "dbo")]
    public class FactorBookMaster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__FactorBo__3214EC2741EDCAC5", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"FactorBookCode", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Factor book code")]
        public string FactorBookCode { get; set; }

        [Column(@"FactorBookDescr", Order = 4, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Factor book descr")]
        public string FactorBookDescr { get; set; }
    }

}
// </auto-generated>
