// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("FiscalYearBeginningBalance", Schema = "dbo")]
    public class FiscalYearBeginningBalance
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_FiscalYearBeginningBalance", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"Year", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Year")]
        public decimal Year { get; set; }

        [Column(@"BeginningBalance", Order = 3, TypeName = "decimal")]
        [Required]
        [Display(Name = "Beginning balance")]
        public decimal BeginningBalance { get; set; }

        [Column(@"YTDCollections", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Ytdc ollections")]
        public decimal YtdCollections { get; set; }

        [Column(@"YTDLosses", Order = 5, TypeName = "decimal")]
        [Required]
        [Display(Name = "Ytdl osses")]
        public decimal YtdLosses { get; set; }

        [Column(@"YTDGains", Order = 6, TypeName = "decimal")]
        [Required]
        [Display(Name = "Ytdg ains")]
        public decimal YtdGains { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column(@"YTDBalance", Order = 7, TypeName = "decimal")]
        [Display(Name = "Ytdb alance")]
        public decimal? YtdBalance { get; private set; }

        [Column(@"AuditFiscalYearId", Order = 8, TypeName = "int")]
        [Required]
        [Display(Name = "Audit fiscal year ID")]
        public int AuditFiscalYearId { get; set; }

        [ForeignKey("AuditFiscalYearId")] public virtual AuditFiscalYear AuditFiscalYear { get; set; }
    }

}
// </auto-generated>
