// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("FlaggingFullDetails", Schema = "dbo")]
    public class FlaggingFullDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Sequence", Order = 4, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Sequence")]
        public decimal Sequence { get; set; }

        [Column(@"FlaggingDetailYear", Order = 5, TypeName = "decimal")]
        [Display(Name = "Flagging detail year")]
        public decimal? FlaggingDetailYear { get; set; }

        [Column(@"FlagComment", Order = 6, TypeName = "char")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Flag comment")]
        public string FlagComment { get; set; }

        [Column(@"FlagStartDate", Order = 7, TypeName = "date")]
        [Display(Name = "Flag start date")]
        public System.DateTime? FlagStartDate { get; set; }

        [Column(@"FlagEndDate", Order = 8, TypeName = "date")]
        [Display(Name = "Flag end date")]
        public System.DateTime? FlagEndDate { get; set; }

        [Column(@"FlagPotentialTaxLiab", Order = 9, TypeName = "decimal")]
        [Display(Name = "Flag potential tax liab")]
        public decimal? FlagPotentialTaxLiab { get; set; }

        [Column(@"FlaggingCode", Order = 10, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Flagging code")]
        public string FlaggingCode { get; set; }

        [Column(@"FlaggingMasterId", Order = 11, TypeName = "int")]
        [Display(Name = "Flagging master ID")]
        public int? FlaggingMasterId { get; set; }

        [Column(@"FlagDescription", Order = 12, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Flag description")]
        public string FlagDescription { get; set; }
    }

}
// </auto-generated>
