// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandAssessmentSgmtAdjs", Schema = "dbo")]
    public class LandAssessmentSgmtAdj
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__LandAsse__3214EC270E6E26BF", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"LandTypeMS", Order = 4, TypeName = "char")]
        [Required]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land type ms")]
        public string LandTypeMs { get; set; }

        [Column(@"LandApprSeq", Order = 5, TypeName = "decimal")]
        [Required]
        [Display(Name = "Land appr seq")]
        public decimal LandApprSeq { get; set; }

        [Column(@"Sequence", Order = 6, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence")]
        public decimal Sequence { get; set; }

        [Column(@"LandSgmtAdjst", Order = 7, TypeName = "numeric")]
        [Display(Name = "Land sgmt adjst")]
        public decimal? LandSgmtAdjst { get; set; }

        [Column(@"LandSgmtAdjstPct", Order = 8, TypeName = "decimal")]
        [Display(Name = "Land sgmt adjst pct")]
        public decimal? LandSgmtAdjstPct { get; set; }

        [Column(@"PropCharCode", Order = 9, TypeName = "char")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Prop char code")]
        public string PropCharCode { get; set; }
    }

}
// </auto-generated>
