// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandAssessmentMsav", Schema = "dbo")]
    public class LandAssessmentMsav
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LandApprSeq", Order = 4, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Land appr seq")]
        public decimal LandApprSeq { get; set; }

        [Column(@"LandApprSize1", Order = 5, TypeName = "decimal")]
        [Display(Name = "Land appr size 1")]
        public decimal? LandApprSize1 { get; set; }

        [Column(@"LandApprSize2", Order = 6, TypeName = "decimal")]
        [Display(Name = "Land appr size 2")]
        public decimal? LandApprSize2 { get; set; }

        [Column(@"MsavBaseLandValue", Order = 7, TypeName = "decimal")]
        [Display(Name = "Msav base land value")]
        public decimal? MsavBaseLandValue { get; set; }

        [Column(@"MsavCurrentLandValue", Order = 8, TypeName = "decimal")]
        [Display(Name = "Msav current land value")]
        public decimal? MsavCurrentLandValue { get; set; }

        [Column(@"CostPerUnit", Order = 9, TypeName = "numeric")]
        [Display(Name = "Cost per unit")]
        public decimal? CostPerUnit { get; set; }

        [Column(@"LumpSumValue", Order = 10, TypeName = "numeric")]
        [Display(Name = "Lump sum value")]
        public decimal? LumpSumValue { get; set; }

        [Column(@"LandApprAssessValue", Order = 11, TypeName = "decimal")]
        [Display(Name = "Land appr assess value")]
        public decimal? LandApprAssessValue { get; set; }

        [Column(@"NoTrendFlag", Order = 12, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "No trend flag")]
        public string NoTrendFlag { get; set; }

        [Column(@"LandCalcMthd", Order = 13, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land calc mthd")]
        public string LandCalcMthd { get; set; }

        [Column(@"ExemFlag", Order = 14, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Exem flag")]
        public string ExemFlag { get; set; }

        [Column(@"LandTypeFarmNonFarm", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land type farm non farm")]
        public string LandTypeFarmNonFarm { get; set; }

        [Column(@"MsavLandValue", Order = 16, TypeName = "decimal")]
        [Display(Name = "Msav land value")]
        public decimal? MsavLandValue { get; set; }

        [Column(@"M50LandValue", Order = 17, TypeName = "decimal")]
        [Display(Name = "M 50 land value")]
        public decimal? M50LandValue { get; set; }

        [Column(@"ValAreaCode", Order = 18, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Val area code")]
        public string ValAreaCode { get; set; }

        [Column(@"LandType", Order = 19, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Land type")]
        public string LandType { get; set; }

        [Column(@"LandClassCode", Order = 20, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Land class code")]
        public string LandClassCode { get; set; }

        [Column(@"PropClassCode", Order = 21, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Prop class code")]
        public string PropClassCode { get; set; }
    }

}
// </auto-generated>
