// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandApprDetails", Schema = "dbo")]
    public class LandApprDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__LandAppr__3214EC273E1D39E1", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"AppraisalDate", Order = 4, TypeName = "date")]
        [Display(Name = "Appraisal date")]
        public System.DateTime? AppraisalDate { get; set; }

        [Column(@"PartOfTotl", Order = 5, TypeName = "decimal")]
        [Display(Name = "Part of totl")]
        public decimal? PartOfTotl { get; set; }

        [Column(@"ApprsrCode", Order = 6, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Apprsr code")]
        public string ApprsrCode { get; set; }

        [Column(@"LandRealMktValue", Order = 7, TypeName = "decimal")]
        [Display(Name = "Land real mkt value")]
        public decimal? LandRealMktValue { get; set; }
    }

}
// </auto-generated>
