// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandAssessmentFullDetails", Schema = "dbo")]
    public class LandAssessmentFullDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LandAssessmentId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Land assessment ID")]
        public int LandAssessmentId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LandTypeMS", Order = 4, TypeName = "char")]
        [Required]
        [MaxLength(1)]
        [StringLength(1)]
        [Key]
        [Display(Name = "Land type ms")]
        public string LandTypeMs { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LandApprSeq", Order = 5, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Land appr seq")]
        public decimal LandApprSeq { get; set; }

        [Column(@"LandApprSize1", Order = 6, TypeName = "decimal")]
        [Display(Name = "Land appr size 1")]
        public decimal? LandApprSize1 { get; set; }

        [Column(@"CostPerUnit", Order = 7, TypeName = "numeric")]
        [Display(Name = "Cost per unit")]
        public decimal? CostPerUnit { get; set; }

        [Column(@"LandApprAssessValue", Order = 8, TypeName = "decimal")]
        [Display(Name = "Land appr assess value")]
        public decimal? LandApprAssessValue { get; set; }

        [Column(@"YearAppraised", Order = 9, TypeName = "decimal")]
        [Display(Name = "Year appraised")]
        public decimal? YearAppraised { get; set; }

        [Column(@"NoTrendFlag", Order = 10, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "No trend flag")]
        public string NoTrendFlag { get; set; }

        [Column(@"TotlLandSgmtAdj", Order = 11, TypeName = "decimal")]
        [Display(Name = "Totl land sgmt adj")]
        public decimal? TotlLandSgmtAdj { get; set; }

        [Column(@"LandCalcMthd", Order = 12, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land calc mthd")]
        public string LandCalcMthd { get; set; }

        [Column(@"ExemFlag", Order = 13, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Exem flag")]
        public string ExemFlag { get; set; }

        [Column(@"ValAreaCode", Order = 14, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Val area code")]
        public string ValAreaCode { get; set; }

        [Column(@"LandType", Order = 15, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Land type")]
        public string LandType { get; set; }

        [Column(@"LandClassCode", Order = 16, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Land class code")]
        public string LandClassCode { get; set; }

        [Column(@"PropClassCode", Order = 17, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Prop class code")]
        public string PropClassCode { get; set; }

        [Column(@"LandApprDetailsId", Order = 18, TypeName = "int")]
        [Display(Name = "Land appr details ID")]
        public int? LandApprDetailsId { get; set; }

        [Column(@"AppraisalDate", Order = 19, TypeName = "date")]
        [Display(Name = "Appraisal date")]
        public System.DateTime? AppraisalDate { get; set; }

        [Column(@"PartOfTotl", Order = 20, TypeName = "decimal")]
        [Display(Name = "Part of totl")]
        public decimal? PartOfTotl { get; set; }

        [Column(@"ApprsrCode", Order = 21, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Apprsr code")]
        public string ApprsrCode { get; set; }

        [Column(@"LandAprsPropCharItemsId", Order = 22, TypeName = "int")]
        [Display(Name = "Land aprs prop char items ID")]
        public int? LandAprsPropCharItemsId { get; set; }

        [Column(@"LandPropCharItem01", Order = 23, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 01")]
        public string LandPropCharItem01 { get; set; }

        [Column(@"LandPropCharItem02", Order = 24, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 02")]
        public string LandPropCharItem02 { get; set; }

        [Column(@"LandPropCharItem03", Order = 25, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 03")]
        public string LandPropCharItem03 { get; set; }

        [Column(@"LandPropCharItem04", Order = 26, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 04")]
        public string LandPropCharItem04 { get; set; }

        [Column(@"LandPropCharItem05", Order = 27, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 05")]
        public string LandPropCharItem05 { get; set; }

        [Column(@"LandPropCharItem06", Order = 28, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 06")]
        public string LandPropCharItem06 { get; set; }

        [Column(@"LandPropCharItem07", Order = 29, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 07")]
        public string LandPropCharItem07 { get; set; }

        [Column(@"LandPropCharItem08", Order = 30, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 08")]
        public string LandPropCharItem08 { get; set; }

        [Column(@"LandPropCharItem09", Order = 31, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 09")]
        public string LandPropCharItem09 { get; set; }

        [Column(@"LandPropCharItem10", Order = 32, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 10")]
        public string LandPropCharItem10 { get; set; }

        [Column(@"LandPropCharItem11", Order = 33, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 11")]
        public string LandPropCharItem11 { get; set; }

        [Column(@"LandPropCharItem12", Order = 34, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 12")]
        public string LandPropCharItem12 { get; set; }

        [Column(@"LandPropCharItem13", Order = 35, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 13")]
        public string LandPropCharItem13 { get; set; }

        [Column(@"LandPropCharItem14", Order = 36, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land prop char item 14")]
        public string LandPropCharItem14 { get; set; }
    }

}
// </auto-generated>
