// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandType", Schema = "dbo")]
    public class LandType
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__LandType__3214EC272180FB33", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"LandType", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Land type")]
        public string LandType_ { get; set; }

        [Column(@"LandTypeDescr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Land type descr")]
        public string LandTypeDescr { get; set; }

        [Column(@"LandTypeFarmNonFarm", Order = 4, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Land type farm non farm")]
        public string LandTypeFarmNonFarm { get; set; }

        [Column(@"CountyNumber", Order = 5, TypeName = "numeric")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }

        [Column(@"TrendingTableToUse", Order = 6, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Trending table to use")]
        public string TrendingTableToUse { get; set; }

        [Column(@"MsavTablesStatus", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Msav tables status")]
        public string MsavTablesStatus { get; set; }
    }

}
// </auto-generated>
