// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("LandClass", Schema = "dbo")]
    public class LandClass
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LandClassCode", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(6)]
        [StringLength(6)]
        [Key]
        [Display(Name = "Land class code")]
        public string LandClassCode { get; set; }

        [Column(@"LandClassDescription", Order = 3, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Land class description")]
        public string LandClassDescription { get; set; }

        [Column(@"TrendingTableToUse", Order = 4, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Trending table to use")]
        public string TrendingTableToUse { get; set; }

        [Column(@"MsavTablesStatus", Order = 5, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Msav tables status")]
        public string MsavTablesStatus { get; set; }
    }

}
// </auto-generated>
