// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("MobileHome", Schema = "dbo")]
    public class MobileHome
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__MobileHo__3214EC2720C1E124", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Seq", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Seq")]
        public decimal Seq { get; set; }

        [Column(@"XNmbr", Order = 5, TypeName = "char")]
        [MaxLength(8)]
        [StringLength(8)]
        [Display(Name = "Xn mbr")]
        public string XNmbr { get; set; }

        [Column(@"MobileHomeId", Order = 6, TypeName = "decimal")]
        [Display(Name = "Mobile home ID")]
        public decimal? MobileHomeId { get; set; }

        [Column(@"YearBuilt", Order = 7, TypeName = "decimal")]
        [Display(Name = "Year built")]
        public decimal? YearBuilt { get; set; }

        [Column(@"LocCostMdfr", Order = 8, TypeName = "decimal")]
        [Display(Name = "Loc cost mdfr")]
        public decimal? LocCostMdfr { get; set; }

        [Column(@"MobHomeWdth", Order = 9, TypeName = "decimal")]
        [Display(Name = "Mob home wdth")]
        public decimal? MobHomeWdth { get; set; }

        [Column(@"MobHomeLngth", Order = 10, TypeName = "decimal")]
        [Display(Name = "Mob home lngth")]
        public decimal? MobHomeLngth { get; set; }

        [Column(@"MobHomeMnfr", Order = 11, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Mob home mnfr")]
        public string MobHomeMnfr { get; set; }

        [Column(@"MobHomeRollType", Order = 12, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Mob home roll type")]
        public string MobHomeRollType { get; set; }

        [Column(@"MobHomeSizeFlag", Order = 13, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Mob home size flag")]
        public string MobHomeSizeFlag { get; set; }

        [Column(@"MobHomeMrktVal", Order = 14, TypeName = "decimal")]
        [Display(Name = "Mob home mrkt val")]
        public decimal? MobHomeMrktVal { get; set; }

        [Column(@"MhClass", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Mh class")]
        public string MhClass { get; set; }

        [Column(@"MhNmbrOfRmsLivg", Order = 16, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms livg")]
        public decimal? MhNmbrOfRmsLivg { get; set; }

        [Column(@"MhNmbrOfRmsBdrm", Order = 17, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms bdrm")]
        public decimal? MhNmbrOfRmsBdrm { get; set; }

        [Column(@"MhNmbrOfRmsBath", Order = 18, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms bath")]
        public decimal? MhNmbrOfRmsBath { get; set; }

        [Column(@"MhNmbrOfRmsKtch", Order = 19, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms ktch")]
        public decimal? MhNmbrOfRmsKtch { get; set; }

        [Column(@"MhNmbrOfRmsDing", Order = 20, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms ding")]
        public decimal? MhNmbrOfRmsDing { get; set; }

        [Column(@"MhNmbrOfRmsUtil", Order = 21, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms util")]
        public decimal? MhNmbrOfRmsUtil { get; set; }

        [Column(@"MhNmbrOfRmsOthr", Order = 22, TypeName = "decimal")]
        [Display(Name = "Mh nmbr of rms othr")]
        public decimal? MhNmbrOfRmsOthr { get; set; }

        [Column(@"MhFrplcs", Order = 23, TypeName = "decimal")]
        [Display(Name = "Mh frplcs")]
        public decimal? MhFrplcs { get; set; }

        [Column(@"MhPhysDepr", Order = 24, TypeName = "decimal")]
        [Display(Name = "Mh phys depr")]
        public decimal? MhPhysDepr { get; set; }

        [Column(@"FuncDepr", Order = 25, TypeName = "decimal")]
        [Display(Name = "Func depr")]
        public decimal? FuncDepr { get; set; }

        [Column(@"MhMiscDepr", Order = 26, TypeName = "decimal")]
        [Display(Name = "Mh misc depr")]
        public decimal? MhMiscDepr { get; set; }

        [Column(@"QltyAdjstPct", Order = 27, TypeName = "decimal")]
        [Display(Name = "Qlty adjst pct")]
        public decimal? QltyAdjstPct { get; set; }

        [Column(@"AreaAdjst", Order = 28, TypeName = "decimal")]
        [Display(Name = "Area adjst")]
        public decimal? AreaAdjst { get; set; }

        [Column(@"EffctvYear", Order = 29, TypeName = "decimal")]
        [Display(Name = "Effctv year")]
        public decimal? EffctvYear { get; set; }

        [Column(@"YearAppraised", Order = 30, TypeName = "decimal")]
        [Display(Name = "Year appraised")]
        public decimal? YearAppraised { get; set; }

        [Column(@"BaseApprYear", Order = 31, TypeName = "decimal")]
        [Display(Name = "Base appr year")]
        public decimal? BaseApprYear { get; set; }

        [Column(@"InspctSts", Order = 32, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Inspct sts")]
        public string InspctSts { get; set; }

        [Column(@"ApprslDate", Order = 33, TypeName = "decimal")]
        [Display(Name = "Apprsl date")]
        public decimal? ApprslDate { get; set; }

        [Column(@"AreaSqLnFeet", Order = 34, TypeName = "decimal")]
        [Display(Name = "Area sq ln feet")]
        public decimal? AreaSqLnFeet { get; set; }

        [Column(@"InvntrTotVal", Order = 35, TypeName = "decimal")]
        [Display(Name = "Invntr tot val")]
        public decimal? InvntrTotVal { get; set; }

        [Column(@"PrctGood", Order = 36, TypeName = "decimal")]
        [Display(Name = "Prct good")]
        public decimal? PrctGood { get; set; }

        [Column(@"FctrBookYear", Order = 37, TypeName = "numeric")]
        [Display(Name = "Fctr book year")]
        public decimal? FctrBookYear { get; set; }

        [Column(@"SpaceNumber", Order = 38, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Space number")]
        public string SpaceNumber { get; set; }

        [Column(@"Condition", Order = 39, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Condition")]
        public string Condition { get; set; }

        [Column(@"ConditionQualifier", Order = 40, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Condition qualifier")]
        public string ConditionQualifier { get; set; }

        [Column(@"SeqCounter", Order = 41, TypeName = "decimal")]
        [Display(Name = "Seq counter")]
        public decimal? SeqCounter { get; set; }

        [Column(@"CostPerUnit", Order = 42, TypeName = "numeric")]
        [Display(Name = "Cost per unit")]
        public decimal? CostPerUnit { get; set; }

        [Column(@"MobHomeTipoutLngth", Order = 43, TypeName = "decimal")]
        [Display(Name = "Mob home tipout lngth")]
        public decimal? MobHomeTipoutLngth { get; set; }

        [Column(@"MobHomeTipoutWidth", Order = 44, TypeName = "decimal")]
        [Display(Name = "Mob home tipout width")]
        public decimal? MobHomeTipoutWidth { get; set; }

        [Column(@"SeqBinding", Order = 45, TypeName = "decimal")]
        [Display(Name = "Seq binding")]
        public decimal? SeqBinding { get; set; }

        [Column(@"MhBaseCost", Order = 46, TypeName = "decimal")]
        [Display(Name = "Mh base cost")]
        public decimal? MhBaseCost { get; set; }

        [Column(@"MhSerial", Order = 47, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Mh serial")]
        public string MhSerial { get; set; }

        [Column(@"FctrBookCode", Order = 48, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Fctr book code")]
        public string FctrBookCode { get; set; }

        [Column(@"AcctNmbr01431", Order = 49, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr 01431")]
        public string AcctNmbr01431 { get; set; }

        [Column(@"PropClassCode", Order = 50, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Prop class code")]
        public string PropClassCode { get; set; }

        [Column(@"ApprsrCode", Order = 51, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Apprsr code")]
        public string ApprsrCode { get; set; }

        [Column(@"HomesteadFlag", Order = 52, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Homestead flag")]
        public string HomesteadFlag { get; set; }
    }

}
// </auto-generated>
