// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropOther", Schema = "dbo")]
    public class PersonalPropOther
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Personal__3214EC277E37BEF6", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Sequence5", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence 5")]
        public decimal Sequence5 { get; set; }

        [Column(@"PpOthrItemDesc", Order = 5, TypeName = "char")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Pp othr item desc")]
        public string PpOthrItemDesc { get; set; }

        [Column(@"PpOthrIdNmbr", Order = 6, TypeName = "char")]
        [MaxLength(14)]
        [StringLength(14)]
        [Display(Name = "Pp othr ID nmbr")]
        public string PpOthrIdNmbr { get; set; }

        [Column(@"PpOthrModlYear", Order = 7, TypeName = "decimal")]
        [Display(Name = "Pp othr modl year")]
        public decimal? PpOthrModlYear { get; set; }

        [Column(@"PpOthrYearPrch", Order = 8, TypeName = "decimal")]
        [Display(Name = "Pp othr year prch")]
        public decimal? PpOthrYearPrch { get; set; }

        [Column(@"PpOthrCostEach", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp othr cost each")]
        public decimal? PpOthrCostEach { get; set; }

        [Column(@"PpOthrQnty", Order = 10, TypeName = "decimal")]
        [Display(Name = "Pp othr qnty")]
        public decimal? PpOthrQnty { get; set; }

        [Column(@"PpOthrMrktVal", Order = 11, TypeName = "decimal")]
        [Display(Name = "Pp othr mrkt val")]
        public decimal? PpOthrMrktVal { get; set; }

        [Column(@"DrcFlag", Order = 12, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Drc flag")]
        public string DrcFlag { get; set; }

        [Column(@"PpOthrPurcDate", Order = 13, TypeName = "date")]
        [Display(Name = "Pp othr purc date")]
        public System.DateTime? PpOthrPurcDate { get; set; }

        [Column(@"PpCategoryCode", Order = 14, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Pp category code")]
        public string PpCategoryCode { get; set; }
    }

}
// </auto-generated>
