// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropNonInvent", Schema = "dbo")]
    public class PersonalPropNonInvent
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Personal__3214EC277A672E12", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Sequence4", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence 4")]
        public decimal Sequence4 { get; set; }

        [Column(@"PpNonGenlOffcSupp", Order = 5, TypeName = "decimal")]
        [Display(Name = "Pp non genl offc supp")]
        public decimal? PpNonGenlOffcSupp { get; set; }

        [Column(@"PpNonMntSppl", Order = 6, TypeName = "decimal")]
        [Display(Name = "Pp non mnt sppl")]
        public decimal? PpNonMntSppl { get; set; }

        [Column(@"PpNonOprtgSppl", Order = 7, TypeName = "decimal")]
        [Display(Name = "Pp non oprtg sppl")]
        public decimal? PpNonOprtgSppl { get; set; }

        [Column(@"PpNonSparPrts", Order = 8, TypeName = "decimal")]
        [Display(Name = "Pp non spar prts")]
        public decimal? PpNonSparPrts { get; set; }

        [Column(@"PpNonOthrNonInvn", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp non othr non invn")]
        public decimal? PpNonOthrNonInvn { get; set; }

        [Column(@"PpNonOwnrMrktVal", Order = 10, TypeName = "decimal")]
        [Display(Name = "Pp non ownr mrkt val")]
        public decimal? PpNonOwnrMrktVal { get; set; }

        [Column(@"PpNonPurcDate", Order = 11, TypeName = "date")]
        [Display(Name = "Pp non purc date")]
        public System.DateTime? PpNonPurcDate { get; set; }
    }

}
// </auto-generated>
