// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropRentDetail", Schema = "dbo")]
    public class PersonalPropRentDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Sequence5", Order = 4, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Sequence 5")]
        public decimal Sequence5 { get; set; }

        [Column(@"PpRentId", Order = 5, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp rent ID")]
        public string PpRentId { get; set; }

        [Column(@"PpRentModlYear", Order = 6, TypeName = "decimal")]
        [Display(Name = "Pp rent modl year")]
        public decimal? PpRentModlYear { get; set; }

        [Column(@"PpRentFilrSts", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp rent filr sts")]
        public string PpRentFilrSts { get; set; }

        [Column(@"PpRentPayrSts", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp rent payr sts")]
        public string PpRentPayrSts { get; set; }

        [Column(@"PpRentAnnlLeas", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp rent annl leas")]
        public decimal? PpRentAnnlLeas { get; set; }

        [Column(@"PpRentDate", Order = 10, TypeName = "date")]
        [Display(Name = "Pp rent date")]
        public System.DateTime? PpRentDate { get; set; }

        [Column(@"PpRentAgrmntLgth", Order = 11, TypeName = "decimal")]
        [Display(Name = "Pp rent agrmnt lgth")]
        public decimal? PpRentAgrmntLgth { get; set; }

        [Column(@"PpOrigCost", Order = 12, TypeName = "decimal")]
        [Display(Name = "Pp orig cost")]
        public decimal? PpOrigCost { get; set; }

        [Column(@"PpRentQnty", Order = 13, TypeName = "decimal")]
        [Display(Name = "Pp rent qnty")]
        public decimal? PpRentQnty { get; set; }

        [Column(@"PpRentItemMrktValue", Order = 14, TypeName = "decimal")]
        [Display(Name = "Pp rent item mrkt value")]
        public decimal? PpRentItemMrktValue { get; set; }

        [Column(@"DrcFlag", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Drc flag")]
        public string DrcFlag { get; set; }

        [Column(@"PpCategoryCode", Order = 16, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Pp category code")]
        public string PpCategoryCode { get; set; }

        [Column(@"SecondPartyAcctAcctNmb", Order = 17, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Second party acct acct nmb")]
        public string SecondPartyAcctAcctNmb { get; set; }
    }

}
// </auto-generated>
