// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropLibrary", Schema = "dbo")]
    public class PersonalPropLibrary
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Personal__3214EC2776969D2E", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Sequence4", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence 4")]
        public decimal Sequence4 { get; set; }

        [Column(@"PpLibrType", Order = 5, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Pp libr type")]
        public string PpLibrType { get; set; }

        [Column(@"PpLibrSetTtle", Order = 6, TypeName = "char")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Pp libr set ttle")]
        public string PpLibrSetTtle { get; set; }

        [Column(@"PpLibrCmpltSts", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp libr cmplt sts")]
        public string PpLibrCmpltSts { get; set; }

        [Column(@"PpLibrOfVlms", Order = 8, TypeName = "decimal")]
        [Display(Name = "Pp libr of vlms")]
        public decimal? PpLibrOfVlms { get; set; }

        [Column(@"PpLibrPrchPrc", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp libr prch prc")]
        public decimal? PpLibrPrchPrc { get; set; }

        [Column(@"PpLibrMrktVal", Order = 10, TypeName = "decimal")]
        [Display(Name = "Pp libr mrkt val")]
        public decimal? PpLibrMrktVal { get; set; }

        [Column(@"PpLibrPurcDate", Order = 11, TypeName = "date")]
        [Display(Name = "Pp libr purc date")]
        public System.DateTime? PpLibrPurcDate { get; set; }
    }

}
// </auto-generated>
