// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropValues", Schema = "dbo")]
    public class PersonalPropValue
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__Personal__3214EC2709A971A2", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"PpLine1Total", Order = 4, TypeName = "decimal")]
        [Display(Name = "Pp line 1 total")]
        public decimal? PpLine1Total { get; set; }

        [Column(@"PpLine2Total", Order = 5, TypeName = "decimal")]
        [Display(Name = "Pp line 2 total")]
        public decimal? PpLine2Total { get; set; }

        [Column(@"PpLine3Total", Order = 6, TypeName = "decimal")]
        [Display(Name = "Pp line 3 total")]
        public decimal? PpLine3Total { get; set; }

        [Column(@"PpLine4Total", Order = 7, TypeName = "decimal")]
        [Display(Name = "Pp line 4 total")]
        public decimal? PpLine4Total { get; set; }

        [Column(@"PpLine5Total", Order = 8, TypeName = "decimal")]
        [Display(Name = "Pp line 5 total")]
        public decimal? PpLine5Total { get; set; }

        [Column(@"PpLine6Total", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp line 6 total")]
        public decimal? PpLine6Total { get; set; }

        [Column(@"RealXRefAccountAcctN", Order = 10, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Real xr ef account acct n")]
        public string RealXRefAccountAcctN { get; set; }
    }

}
// </auto-generated>
