// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropDetail", Schema = "dbo")]
    public class PersonalPropDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"PpDetlSitusAdrs", Order = 4, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp detl situs adrs")]
        public string PpDetlSitusAdrs { get; set; }

        [Column(@"PpDetlDateOfOrgn", Order = 5, TypeName = "date")]
        [Display(Name = "Pp detl date of orgn")]
        public System.DateTime? PpDetlDateOfOrgn { get; set; }

        [Column(@"PpDetlBusType", Order = 6, TypeName = "char")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Pp detl bus type")]
        public string PpDetlBusType { get; set; }

        [Column(@"PpDetlPrrYrRtrn", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp detl prr yr rtrn")]
        public string PpDetlPrrYrRtrn { get; set; }

        [Column(@"PpDetlSaleDate", Order = 8, TypeName = "date")]
        [Display(Name = "Pp detl sale date")]
        public System.DateTime? PpDetlSaleDate { get; set; }

        [Column(@"PpDetlNewOwnrName", Order = 9, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp detl new ownr name")]
        public string PpDetlNewOwnrName { get; set; }

        [Column(@"PpDetlFirmName", Order = 10, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp detl firm name")]
        public string PpDetlFirmName { get; set; }

        [Column(@"PpDetlAsmdBusNam", Order = 11, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp detl asmd bus nam")]
        public string PpDetlAsmdBusNam { get; set; }

        [Column(@"PpDetlAsmdBusAdd", Order = 12, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp detl asmd bus add")]
        public string PpDetlAsmdBusAdd { get; set; }

        [Column(@"PpDetlFlngSts", Order = 13, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp detl flng sts")]
        public string PpDetlFlngSts { get; set; }

        [Column(@"PhoneNumber", Order = 14, TypeName = "decimal")]
        [Phone]
        [Display(Name = "Phone number")]
        public decimal? PhoneNumber { get; set; }

        [Column(@"ReturnFiledStatus", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Return filed status")]
        public string ReturnFiledStatus { get; set; }

        [Column(@"DateReturnFiled", Order = 16, TypeName = "date")]
        [Display(Name = "Date return filed")]
        public System.DateTime? DateReturnFiled { get; set; }

        [Column(@"WorkedStatus", Order = 17, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Worked status")]
        public string WorkedStatus { get; set; }

        [Column(@"ZipCode", Order = 18, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Zip code")]
        public string ZipCode { get; set; }

        [Column(@"ApprsrCode", Order = 19, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Apprsr code")]
        public string ApprsrCode { get; set; }
    }

}
// </auto-generated>
