// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("PersonalPropFloating", Schema = "dbo")]
    public class PersonalPropFloating
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Sequence4", Order = 4, TypeName = "decimal")]
        [Required]
        [Key]
        [Display(Name = "Sequence 4")]
        public decimal Sequence4 { get; set; }

        [Column(@"PpFltRgstNmbr", Order = 5, TypeName = "char")]
        [MaxLength(14)]
        [StringLength(14)]
        [Display(Name = "Pp flt rgst nmbr")]
        public string PpFltRgstNmbr { get; set; }

        [Column(@"PpFlotDatePrch", Order = 6, TypeName = "date")]
        [Display(Name = "Pp flot date prch")]
        public System.DateTime? PpFlotDatePrch { get; set; }

        [Column(@"PpFlotCntrctType", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp flot cntrct type")]
        public string PpFlotCntrctType { get; set; }

        [Column(@"PpFlotCntrctOwnr", Order = 8, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Pp flot cntrct ownr")]
        public string PpFlotCntrctOwnr { get; set; }

        [Column(@"PpFlotPrchPrc", Order = 9, TypeName = "decimal")]
        [Display(Name = "Pp flot prch prc")]
        public decimal? PpFlotPrchPrc { get; set; }

        [Column(@"PpFlotMoorLocn", Order = 10, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Pp flot moor locn")]
        public string PpFlotMoorLocn { get; set; }

        [Column(@"PpFlotTypeOfProp", Order = 11, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp flot type of prop")]
        public string PpFlotTypeOfProp { get; set; }

        [Column(@"PpFlotVsslName", Order = 12, TypeName = "char")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Pp flot vssl name")]
        public string PpFlotVsslName { get; set; }

        [Column(@"PpFlotMrktVal", Order = 13, TypeName = "decimal")]
        [Display(Name = "Pp flot mrkt val")]
        public decimal? PpFlotMrktVal { get; set; }

        [Column(@"PpFlotMdlYear", Order = 14, TypeName = "decimal")]
        [Display(Name = "Pp flot mdl year")]
        public decimal? PpFlotMdlYear { get; set; }

        [Column(@"PpFlotCond", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pp flot cond")]
        public string PpFlotCond { get; set; }
    }

}
// </auto-generated>
