// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("SalesMaster", Schema = "dbo")]
    public class SalesMaster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__SalesMas__3214EC277D0E9093", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"SaleIdentification", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Sale identification")]
        public string SaleIdentification { get; set; }

        [Column(@"FactorBookDigit1", Order = 3, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Factor book digit 1")]
        public string FactorBookDigit1 { get; set; }

        [Column(@"FactorBookDigit2", Order = 4, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Factor book digit 2")]
        public string FactorBookDigit2 { get; set; }

        [Column(@"FactorBookDigit3", Order = 5, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Factor book digit 3")]
        public string FactorBookDigit3 { get; set; }

        [Column(@"FactorBookDigit4", Order = 6, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Factor book digit 4")]
        public string FactorBookDigit4 { get; set; }

        [Column(@"PropClassDigit1", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prop class digit 1")]
        public string PropClassDigit1 { get; set; }

        [Column(@"PropClassDigit2", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prop class digit 2")]
        public string PropClassDigit2 { get; set; }

        [Column(@"PropClassDigit3", Order = 9, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prop class digit 3")]
        public string PropClassDigit3 { get; set; }

        [Column(@"PropClassDigit4", Order = 10, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prop class digit 4")]
        public string PropClassDigit4 { get; set; }

        [Column(@"RecordedSalesPrice", Order = 11, TypeName = "decimal")]
        [Display(Name = "Recorded sales price")]
        public decimal? RecordedSalesPrice { get; set; }

        [Column(@"ConfirmedSalesPrice", Order = 12, TypeName = "decimal")]
        [Display(Name = "Confirmed sales price")]
        public decimal? ConfirmedSalesPrice { get; set; }

        [Column(@"ChattelAmount", Order = 13, TypeName = "decimal")]
        [Display(Name = "Chattel amount")]
        public decimal? ChattelAmount { get; set; }

        [Column(@"NetSalesPrice", Order = 14, TypeName = "decimal")]
        [Display(Name = "Net sales price")]
        public decimal? NetSalesPrice { get; set; }

        [Column(@"SaleRatio", Order = 15, TypeName = "decimal")]
        [Display(Name = "Sale ratio")]
        public decimal? SaleRatio { get; set; }

        [Column(@"BuyerName", Order = 16, TypeName = "char")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Buyer name")]
        public string BuyerName { get; set; }

        [Column(@"BuyerAddress1", Order = 17, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Buyer address 1")]
        public string BuyerAddress1 { get; set; }

        [Column(@"BuyerAddress2", Order = 18, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Buyer address 2")]
        public string BuyerAddress2 { get; set; }

        [Column(@"SellerAddress1", Order = 19, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Seller address 1")]
        public string SellerAddress1 { get; set; }

        [Column(@"SellerAddress2", Order = 20, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Seller address 2")]
        public string SellerAddress2 { get; set; }

        [Column(@"SellerName", Order = 21, TypeName = "char")]
        [MaxLength(35)]
        [StringLength(35)]
        [Display(Name = "Seller name")]
        public string SellerName { get; set; }

        [Column(@"ConfirmationStatus", Order = 22, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Confirmation status")]
        public string ConfirmationStatus { get; set; }

        [Column(@"Ref", Order = 23, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Ref")]
        public string Ref { get; set; }

        [Column(@"InterestRate", Order = 24, TypeName = "decimal")]
        [Display(Name = "Interest rate")]
        public decimal? InterestRate { get; set; }

        [Column(@"DownPaymentAmount", Order = 25, TypeName = "decimal")]
        [Display(Name = "Down payment amount")]
        public decimal? DownPaymentAmount { get; set; }

        [Column(@"DurationOfFinancing", Order = 26, TypeName = "decimal")]
        [Display(Name = "Duration of financing")]
        public decimal? DurationOfFinancing { get; set; }

        [Column(@"SaleLandValue", Order = 27, TypeName = "decimal")]
        [Display(Name = "Sale land value")]
        public decimal? SaleLandValue { get; set; }

        [Column(@"SaleImprovementValue", Order = 28, TypeName = "decimal")]
        [Display(Name = "Sale improvement value")]
        public decimal? SaleImprovementValue { get; set; }

        [Column(@"SaleMobHomeValue", Order = 29, TypeName = "decimal")]
        [Display(Name = "Sale mob home value")]
        public decimal? SaleMobHomeValue { get; set; }

        [Column(@"TotalAssessedValue", Order = 30, TypeName = "decimal")]
        [Display(Name = "Total assessed value")]
        public decimal? TotalAssessedValue { get; set; }

        [Column(@"TotalAcres", Order = 31, TypeName = "decimal")]
        [Display(Name = "Total acres")]
        public decimal? TotalAcres { get; set; }

        [Column(@"DateOfConfirmation", Order = 32, TypeName = "date")]
        [Display(Name = "Date of confirmation")]
        public System.DateTime? DateOfConfirmation { get; set; }

        [Column(@"YearAppraised", Order = 33, TypeName = "decimal")]
        [Display(Name = "Year appraised")]
        public decimal? YearAppraised { get; set; }

        [Column(@"CountyNumber", Order = 34, TypeName = "decimal")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }

        [Column(@"PercentGood", Order = 35, TypeName = "decimal")]
        [Display(Name = "Percent good")]
        public decimal? PercentGood { get; set; }

        [Column(@"YearBuilt", Order = 36, TypeName = "decimal")]
        [Display(Name = "Year built")]
        public decimal? YearBuilt { get; set; }

        [Column(@"AssessmentYear", Order = 37, TypeName = "decimal")]
        [Display(Name = "Assessment year")]
        public decimal? AssessmentYear { get; set; }

        [Column(@"SaleDate", Order = 38, TypeName = "date")]
        [Display(Name = "Sale date")]
        public System.DateTime? SaleDate { get; set; }

        [Column(@"MultiAccountFlag", Order = 39, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Multi account flag")]
        public string MultiAccountFlag { get; set; }

        [Column(@"SalesLetterStatus", Order = 40, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Sales letter status")]
        public string SalesLetterStatus { get; set; }

        [Column(@"AreaSquareLinealFeety", Order = 41, TypeName = "decimal")]
        [Display(Name = "Area square lineal feety")]
        public decimal? AreaSquareLinealFeety { get; set; }

        [Column(@"Class", Order = 42, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Class")]
        public string Class { get; set; }

        [Column(@"MobileHomeManufacturer", Order = 43, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Mobile home manufacturer")]
        public string MobileHomeManufacturer { get; set; }

        [Column(@"MobileHomeSize", Order = 44, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Mobile home size")]
        public string MobileHomeSize { get; set; }

        [Column(@"NumberBedrooms", Order = 45, TypeName = "decimal")]
        [Display(Name = "Number bedrooms")]
        public decimal? NumberBedrooms { get; set; }

        [Column(@"NumberBaths", Order = 46, TypeName = "decimal")]
        [Display(Name = "Number baths")]
        public decimal? NumberBaths { get; set; }

        [Column(@"NumberFloors", Order = 47, TypeName = "decimal")]
        [Display(Name = "Number floors")]
        public decimal? NumberFloors { get; set; }

        [Column(@"AtticBasementBoth", Order = 48, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Attic basement both")]
        public string AtticBasementBoth { get; set; }

        [Column(@"SaleCenturyYearMonth", Order = 49, TypeName = "decimal")]
        [Display(Name = "Sale century year month")]
        public decimal? SaleCenturyYearMonth { get; set; }

        [Column(@"ConditionCode", Order = 50, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Condition code")]
        public string ConditionCode { get; set; }

        [Column(@"SecondaryVerificationCode", Order = 51, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Secondary verification code")]
        public string SecondaryVerificationCode { get; set; }

        [Column(@"FinancingCode", Order = 52, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Financing code")]
        public string FinancingCode { get; set; }

        [Column(@"InstrumentCode", Order = 53, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Instrument code")]
        public string InstrumentCode { get; set; }

        [Column(@"BuyerZipCode", Order = 54, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Buyer zip code")]
        public string BuyerZipCode { get; set; }

        [Column(@"SellerZipCode", Order = 55, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Seller zip code")]
        public string SellerZipCode { get; set; }

        [Column(@"AppraiserCode1", Order = 56, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Appraiser code 1")]
        public string AppraiserCode1 { get; set; }

        [Column(@"ValueAreaCode", Order = 57, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Value area code")]
        public string ValueAreaCode { get; set; }

        [Column(@"CodeAreaCode", Order = 58, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Code area code")]
        public string CodeAreaCode { get; set; }

        [Column(@"AppraiserCode2", Order = 59, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Appraiser code 2")]
        public string AppraiserCode2 { get; set; }

        [Column(@"AsmtYear", Order = 60, TypeName = "decimal")]
        [Display(Name = "Asmt year")]
        public decimal? AsmtYear { get; set; }

        [Column(@"MaintenanceAreaCode", Order = 61, TypeName = "decimal")]
        [Display(Name = "Maintenance area code")]
        public decimal? MaintenanceAreaCode { get; set; }

        [Column(@"ZoningCode", Order = 62, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Zoning code")]
        public string ZoningCode { get; set; }

        [Column(@"PropertyClassCode", Order = 63, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Property class code")]
        public string PropertyClassCode { get; set; }

        [Column(@"Twnshp", Order = 64, TypeName = "numeric")]
        [Display(Name = "Twnshp")]
        public decimal? Twnshp { get; set; }

        [Column(@"TwnshpDir", Order = 65, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Twnshp dir")]
        public string TwnshpDir { get; set; }

        [Column(@"Range", Order = 66, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Range")]
        public string Range { get; set; }

        [Column(@"RangDir", Order = 67, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Rang dir")]
        public string RangDir { get; set; }

        [Column(@"Sctn", Order = 68, TypeName = "decimal")]
        [Display(Name = "Sctn")]
        public decimal? Sctn { get; set; }

        [Column(@"QtrSctn", Order = 69, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Qtr sctn")]
        public string QtrSctn { get; set; }

        [Column(@"Prcl", Order = 70, TypeName = "numeric")]
        [Display(Name = "Prcl")]
        public decimal? Prcl { get; set; }

        [Column(@"SpecIntAlph", Order = 71, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Spec int alph")]
        public string SpecIntAlph { get; set; }

        [Column(@"SpecIntNmbr", Order = 72, TypeName = "numeric")]
        [Display(Name = "Spec int nmbr")]
        public decimal? SpecIntNmbr { get; set; }
    }

}
// </auto-generated>
