// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("SalesComments", Schema = "dbo")]
    public class SalesComment
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SaleIdentification", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Sale identification")]
        public string SaleIdentification { get; set; }

        [Column(@"SalesComment1", Order = 3, TypeName = "char")]
        [MaxLength(70)]
        [StringLength(70)]
        [Display(Name = "Sales comment 1")]
        public string SalesComment1 { get; set; }

        [Column(@"SalesComment2", Order = 4, TypeName = "char")]
        [MaxLength(70)]
        [StringLength(70)]
        [Display(Name = "Sales comment 2")]
        public string SalesComment2 { get; set; }
    }

}
// </auto-generated>
