// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("SalesAccounts", Schema = "dbo")]
    public class SalesAccount
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__SalesAcc__3214EC27793DFFAF", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"SaleIdentification", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Sale identification")]
        public string SaleIdentification { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"AcctLandAssessedTotal", Order = 4, TypeName = "decimal")]
        [Display(Name = "Acct land assessed total")]
        public decimal? AcctLandAssessedTotal { get; set; }

        [Column(@"AcctImprovementTotal", Order = 5, TypeName = "decimal")]
        [Display(Name = "Acct improvement total")]
        public decimal? AcctImprovementTotal { get; set; }

        [Column(@"SalesAcres", Order = 6, TypeName = "decimal")]
        [Display(Name = "Sales acres")]
        public decimal? SalesAcres { get; set; }

        [Column(@"PrimeIndicator", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prime indicator")]
        public string PrimeIndicator { get; set; }

        [Column(@"MultiAccountSaleStatus", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Multi account sale status")]
        public string MultiAccountSaleStatus { get; set; }

        [Column(@"CommentsExistStatus", Order = 9, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Comments exist status")]
        public string CommentsExistStatus { get; set; }

        [Column(@"AcctMobileHomeTotal", Order = 10, TypeName = "decimal")]
        [Display(Name = "Acct mobile home total")]
        public decimal? AcctMobileHomeTotal { get; set; }

        [Column(@"Twnshp", Order = 11, TypeName = "numeric")]
        [Display(Name = "Twnshp")]
        public decimal? Twnshp { get; set; }

        [Column(@"TwnshpDir", Order = 12, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Twnshp dir")]
        public string TwnshpDir { get; set; }

        [Column(@"Range", Order = 13, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Range")]
        public string Range { get; set; }

        [Column(@"RangDir", Order = 14, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Rang dir")]
        public string RangDir { get; set; }

        [Column(@"Sctn", Order = 15, TypeName = "decimal")]
        [Display(Name = "Sctn")]
        public decimal? Sctn { get; set; }

        [Column(@"QtrSctn", Order = 16, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Qtr sctn")]
        public string QtrSctn { get; set; }

        [Column(@"Prcl", Order = 17, TypeName = "numeric")]
        [Display(Name = "Prcl")]
        public decimal? Prcl { get; set; }

        [Column(@"SpecIntAlph", Order = 18, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Spec int alph")]
        public string SpecIntAlph { get; set; }

        [Column(@"SpecIntNmbr", Order = 19, TypeName = "numeric")]
        [Display(Name = "Spec int nmbr")]
        public decimal? SpecIntNmbr { get; set; }

        [Column(@"PrimeIndicatorNonDisp", Order = 20, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Prime indicator non disp")]
        public string PrimeIndicatorNonDisp { get; set; }
    }

}
// </auto-generated>
