// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("SpecialAssessDetail", Schema = "dbo")]
    public class SpecialAssessDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__SpecialA__3214EC2738996AB5", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Sequence", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence")]
        public decimal Sequence { get; set; }

        [Column(@"SpecAssessAmount", Order = 5, TypeName = "decimal")]
        [Display(Name = "Spec assess amount")]
        public decimal? SpecAssessAmount { get; set; }

        [Column(@"SpecAssessAcres", Order = 6, TypeName = "decimal")]
        [Display(Name = "Spec assess acres")]
        public decimal? SpecAssessAcres { get; set; }

        [Column(@"SpecAssessCode", Order = 7, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Spec assess code")]
        public string SpecAssessCode { get; set; }
    }

}
// </auto-generated>
