// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("TaxFeeFile", Schema = "dbo")]
    public class TaxFeeFile
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__TaxFeeFi__3214EC27403A8C7D", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AcctNmbr", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"TaxRollYear", Order = 3, TypeName = "numeric")]
        [Required]
        [Display(Name = "Tax roll year")]
        public decimal TaxRollYear { get; set; }

        [Column(@"PayFeeType", Order = 4, TypeName = "char")]
        [Required]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Pay fee type")]
        public string PayFeeType { get; set; }

        [Column(@"TaxFeeSeq", Order = 5, TypeName = "decimal")]
        [Required]
        [Display(Name = "Tax fee seq")]
        public decimal TaxFeeSeq { get; set; }

        [Column(@"TaxFeeWarNum", Order = 6, TypeName = "decimal")]
        [Display(Name = "Tax fee war num")]
        public decimal? TaxFeeWarNum { get; set; }

        [Column(@"TaxFeeAmt", Order = 7, TypeName = "decimal")]
        [Display(Name = "Tax fee amt")]
        public decimal? TaxFeeAmt { get; set; }

        [Column(@"TaxFeeIssueDate", Order = 8, TypeName = "decimal")]
        [Display(Name = "Tax fee issue date")]
        public decimal? TaxFeeIssueDate { get; set; }

        [Column(@"TaxFeeDocDate", Order = 9, TypeName = "decimal")]
        [Display(Name = "Tax fee doc date")]
        public decimal? TaxFeeDocDate { get; set; }

        [Column(@"TaxFeeReleaseDate", Order = 10, TypeName = "decimal")]
        [Display(Name = "Tax fee release date")]
        public decimal? TaxFeeReleaseDate { get; set; }
    }

}
// </auto-generated>
