// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("TaxMasterMaintFile", Schema = "dbo")]
    public class TaxMasterMaintFile
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AcctNmbr", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Key]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"LenderNumber", Order = 3, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Lender number")]
        public string LenderNumber { get; set; }

        [Column(@"LenderSeqNumber", Order = 4, TypeName = "decimal")]
        [Display(Name = "Lender seq number")]
        public decimal? LenderSeqNumber { get; set; }

        [Column(@"TaxMstrLoanInfo", Order = 5, TypeName = "char")]
        [MaxLength(24)]
        [StringLength(24)]
        [Display(Name = "Tax mstr loan info")]
        public string TaxMstrLoanInfo { get; set; }

        [Column(@"TaxMstrTapeExchg", Order = 6, TypeName = "char")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Tax mstr tape exchg")]
        public string TaxMstrTapeExchg { get; set; }

        [Column(@"TaxMstrTaxStatus", Order = 7, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax mstr tax status")]
        public string TaxMstrTaxStatus { get; set; }

        [Column(@"TaxMstrPaymentPlan", Order = 8, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax mstr payment plan")]
        public string TaxMstrPaymentPlan { get; set; }

        [Column(@"TaxMstrFclsDate", Order = 9, TypeName = "date")]
        [Display(Name = "Tax mstr fcls date")]
        public System.DateTime? TaxMstrFclsDate { get; set; }

        [Column(@"TaxMstrJndDate", Order = 10, TypeName = "date")]
        [Display(Name = "Tax mstr jnd date")]
        public System.DateTime? TaxMstrJndDate { get; set; }

        [Column(@"TaxMstrFclsList", Order = 11, TypeName = "char")]
        [MaxLength(4)]
        [StringLength(4)]
        [Display(Name = "Tax mstr fcls list")]
        public string TaxMstrFclsList { get; set; }

        [Column(@"TaxMstrJndCase", Order = 12, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Tax mstr jnd case")]
        public string TaxMstrJndCase { get; set; }

        [Column(@"TaxMstrPullNumber", Order = 13, TypeName = "decimal")]
        [Display(Name = "Tax mstr pull number")]
        public decimal? TaxMstrPullNumber { get; set; }

        [Column(@"BankruptcyCode", Order = 14, TypeName = "char")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Bankruptcy code")]
        public string BankruptcyCode { get; set; }

        [Column(@"BankruptcyCourtFileDte", Order = 15, TypeName = "date")]
        [Display(Name = "Bankruptcy court file dte")]
        public System.DateTime? BankruptcyCourtFileDte { get; set; }

        [Column(@"BankruptcyCourtLastAcc", Order = 16, TypeName = "date")]
        [Display(Name = "Bankruptcy court last acc")]
        public System.DateTime? BankruptcyCourtLastAcc { get; set; }

        [Column(@"BankruptcyOpenCaseSts", Order = 17, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Bankruptcy open case sts")]
        public string BankruptcyOpenCaseSts { get; set; }

        [Column(@"BankruptcyCaseNumber", Order = 18, TypeName = "char")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Bankruptcy case number")]
        public string BankruptcyCaseNumber { get; set; }

        [Column(@"BankruptcyClaimFileDte", Order = 19, TypeName = "date")]
        [Display(Name = "Bankruptcy claim file dte")]
        public System.DateTime? BankruptcyClaimFileDte { get; set; }

        [Column(@"BankruptcyPlnConfirmDt", Order = 20, TypeName = "date")]
        [Display(Name = "Bankruptcy pln confirm dt")]
        public System.DateTime? BankruptcyPlnConfirmDt { get; set; }

        [Column(@"BankruptcyDischargeDate", Order = 21, TypeName = "date")]
        [Display(Name = "Bankruptcy discharge date")]
        public System.DateTime? BankruptcyDischargeDate { get; set; }

        [Column(@"BankruptcyCaseCloseDte", Order = 22, TypeName = "date")]
        [Display(Name = "Bankruptcy case close dte")]
        public System.DateTime? BankruptcyCaseCloseDte { get; set; }

        [Column(@"BankruptcyLastActDate", Order = 23, TypeName = "date")]
        [Display(Name = "Bankruptcy last act date")]
        public System.DateTime? BankruptcyLastActDate { get; set; }

        [Column(@"AttorneyTrusteeSeq", Order = 24, TypeName = "decimal")]
        [Display(Name = "Attorney trustee seq")]
        public decimal? AttorneyTrusteeSeq { get; set; }

        [Column(@"TrusteeAttorneyTrustee", Order = 25, TypeName = "decimal")]
        [Display(Name = "Trustee attorney trustee")]
        public decimal? TrusteeAttorneyTrustee { get; set; }

        [Column(@"PostPetitionYear", Order = 26, TypeName = "numeric")]
        [Display(Name = "Post petition year")]
        public decimal? PostPetitionYear { get; set; }

        [Column(@"RedemptionFeeAmount", Order = 27, TypeName = "decimal")]
        [Display(Name = "Redemption fee amount")]
        public decimal? RedemptionFeeAmount { get; set; }
    }

}
// </auto-generated>
