// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("TaxRoll", Schema = "dbo")]
    public class TaxRoll
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__TaxRoll__3214EC27534D60F1", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AcctNmbr", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"TaxRollYear", Order = 3, TypeName = "numeric")]
        [Required]
        [Display(Name = "Tax roll year")]
        public decimal TaxRollYear { get; set; }

        [Column(@"TaxRollAdvalorem", Order = 4, TypeName = "numeric")]
        [Display(Name = "Tax roll advalorem")]
        public decimal? TaxRollAdvalorem { get; set; }

        [Column(@"TaxRollPaid", Order = 5, TypeName = "numeric")]
        [Display(Name = "Tax roll paid")]
        public decimal? TaxRollPaid { get; set; }

        [Column(@"TaxRollNav", Order = 6, TypeName = "numeric")]
        [Display(Name = "Tax roll nav")]
        public decimal? TaxRollNav { get; set; }

        [Column(@"TaxRollRealMktValue", Order = 7, TypeName = "numeric")]
        [Display(Name = "Tax roll real mkt value")]
        public decimal? TaxRollRealMktValue { get; set; }

        [Column(@"TaxRollStatePay", Order = 8, TypeName = "numeric")]
        [Display(Name = "Tax roll state pay")]
        public decimal? TaxRollStatePay { get; set; }

        [Column(@"TaxRollMobileAt", Order = 9, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax roll mobile at")]
        public string TaxRollMobileAt { get; set; }

        [Column(@"TaxRollRollType", Order = 10, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax roll roll type")]
        public string TaxRollRollType { get; set; }

        [Column(@"TaxRollCodeArea", Order = 11, TypeName = "char")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Tax roll code area")]
        public string TaxRollCodeArea { get; set; }

        [Column(@"TaxRollSpecAmount", Order = 12, TypeName = "numeric")]
        [Display(Name = "Tax roll spec amount")]
        public decimal? TaxRollSpecAmount { get; set; }

        [Column(@"TaxRollOpenBal", Order = 13, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax roll open bal")]
        public string TaxRollOpenBal { get; set; }

        [Column(@"TaxRollSpecSw", Order = 14, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax roll spec sw")]
        public string TaxRollSpecSw { get; set; }

        [Column(@"TaxRollWarFlg", Order = 15, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tax roll war flg")]
        public string TaxRollWarFlg { get; set; }

        [Column(@"TaxRollPenalty", Order = 16, TypeName = "numeric")]
        [Display(Name = "Tax roll penalty")]
        public decimal? TaxRollPenalty { get; set; }

        [Column(@"TaxRollFil21", Order = 17, TypeName = "char")]
        [MaxLength(21)]
        [StringLength(21)]
        [Display(Name = "Tax roll fil 21")]
        public string TaxRollFil21 { get; set; }

        [Column(@"TaxRollNavNew", Order = 18, TypeName = "numeric")]
        [Display(Name = "Tax roll nav new")]
        public decimal? TaxRollNavNew { get; set; }

        [Column(@"TaxRollRmvNew", Order = 19, TypeName = "numeric")]
        [Display(Name = "Tax roll rmv new")]
        public decimal? TaxRollRmvNew { get; set; }
    }

}
// </auto-generated>
