// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("UtilitySummary", Schema = "dbo")]
    public class UtilitySummary
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__UtilityS__3214EC275BE2A6F2", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"AsmtYear", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Asmt year")]
        public decimal AsmtYear { get; set; }

        [Column(@"AcctNmbr", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(9)]
        [StringLength(9)]
        [Display(Name = "Acct nmbr")]
        public string AcctNmbr { get; set; }

        [Column(@"Sequence4", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Sequence 4")]
        public decimal Sequence4 { get; set; }

        [Column(@"UtilType", Order = 5, TypeName = "char")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Util type")]
        public string UtilType { get; set; }

        [Column(@"UtilTotUnits", Order = 6, TypeName = "decimal")]
        [Display(Name = "Util tot units")]
        public decimal? UtilTotUnits { get; set; }

        [Column(@"UtilAssessRateUnit", Order = 7, TypeName = "decimal")]
        [Display(Name = "Util assess rate unit")]
        public decimal? UtilAssessRateUnit { get; set; }

        [Column(@"UtilUnitAssdValue", Order = 8, TypeName = "decimal")]
        [Display(Name = "Util unit assd value")]
        public decimal? UtilUnitAssdValue { get; set; }

        [Column(@"UtilAppealRateUnit", Order = 9, TypeName = "decimal")]
        [Display(Name = "Util appeal rate unit")]
        public decimal? UtilAppealRateUnit { get; set; }

        [Column(@"UtilUnitAppealValue", Order = 10, TypeName = "decimal")]
        [Display(Name = "Util unit appeal value")]
        public decimal? UtilUnitAppealValue { get; set; }

        [Column(@"UtilFinalRateUnit", Order = 11, TypeName = "decimal")]
        [Display(Name = "Util final rate unit")]
        public decimal? UtilFinalRateUnit { get; set; }

        [Column(@"UtilFinalUnitValue", Order = 12, TypeName = "decimal")]
        [Display(Name = "Util final unit value")]
        public decimal? UtilFinalUnitValue { get; set; }

        [Column(@"UtilMavRateUnit", Order = 13, TypeName = "decimal")]
        [Display(Name = "Util mav rate unit")]
        public decimal? UtilMavRateUnit { get; set; }

        [Column(@"UtilMavUnitValue", Order = 14, TypeName = "decimal")]
        [Display(Name = "Util mav unit value")]
        public decimal? UtilMavUnitValue { get; set; }
    }

}
// </auto-generated>
