// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("ValueArea", Schema = "dbo")]
    public class ValueArea
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ValAreaCode", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(3)]
        [StringLength(3)]
        [Key]
        [Display(Name = "Val area code")]
        public string ValAreaCode { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ValAreaDesc", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Key]
        [Display(Name = "Val area desc")]
        public string ValAreaDesc { get; set; }

        [Column(@"FrmNonFrmFlag", Order = 4, TypeName = "char")]
        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Frm non frm flag")]
        public string FrmNonFrmFlag { get; set; }

        [Column(@"CountyNumber", Order = 5, TypeName = "numeric")]
        [Display(Name = "County number")]
        public decimal? CountyNumber { get; set; }

        [Column(@"LocCostMdfr", Order = 6, TypeName = "decimal")]
        [Display(Name = "Loc cost mdfr")]
        public decimal? LocCostMdfr { get; set; }
    }

}
// </auto-generated>
