// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HarneyCounty.Domain.Core.Models
{

    [Table("ZipCodeFile", Schema = "dbo")]
    public class ZipCodeFile
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK__ZipCodeF__3214EC272C3393D0", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"ZipCode", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Zip code")]
        public string ZipCode { get; set; }

        [Column(@"City", Order = 3, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "City")]
        public string City { get; set; }

        [Column(@"State", Order = 4, TypeName = "char")]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "State")]
        public string State { get; set; }

        [Column(@"Country", Order = 5, TypeName = "char")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Country")]
        public string Country { get; set; }
    }

}
// </auto-generated>
