// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class AccountSummaryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AccountSummary>
    {
        public AccountSummaryConfiguration()
            : this("dbo")
        {
        }

        public AccountSummaryConfiguration(string schema)
        {
            Property(x => x.AsmtYear).IsOptional().HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.AcctLandAssessTotl).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctImprTotl).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctSpecAses).IsOptional().HasPrecision(9,2);
            Property(x => x.AcctExmpTotal).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctAcresMkt).IsOptional().HasPrecision(9,3);
            Property(x => x.AcctAcresSpc).IsOptional().HasPrecision(9,3);
            Property(x => x.AcctMobHomeTotl).IsOptional().HasPrecision(7,0);
            Property(x => x.AcctMrktLandTotl).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctImprMrktValTotl).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctExmpMktTotal).IsOptional().HasPrecision(9,0);
            Property(x => x.UtilUnitAssessVal).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine1Total).IsOptional().HasPrecision(9,0);
            Property(x => x.UtilOtherAssessVal).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine2Total).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine3Total).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine4Total).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine5Total).IsOptional().HasPrecision(9,0);
            Property(x => x.PpLine6Total).IsOptional().HasPrecision(9,0);
            Property(x => x.MaximumAssessedValue).IsOptional().HasPrecision(9,0);
            Property(x => x.TaxableAssessedValue).IsOptional().HasPrecision(9,0);
            Property(x => x.MaxSpecAssessedValue).IsOptional().HasPrecision(9,0);
            Property(x => x.TotalExceptions).IsOptional().HasPrecision(9,0);
            Property(x => x.Rmv).IsOptional().HasPrecision(9,0);
            Property(x => x.Sav).IsOptional().HasPrecision(9,0);
            Property(x => x.MsavLand).IsOptional().HasPrecision(9,0);
            Property(x => x.ExceptionsMav).IsOptional().HasPrecision(9,0);
            Property(x => x.ExceptionsMsav).IsOptional().HasPrecision(9,0);
            Property(x => x.ExemptionsMav).IsOptional().HasPrecision(9,0);
            Property(x => x.ExemptionsMsav).IsOptional().HasPrecision(9,0);
            Property(x => x.MsavBaseNsaLand).IsOptional().HasPrecision(9,0);
            Property(x => x.MsavBaseImprovements).IsOptional().HasPrecision(9,0);
            Property(x => x.MsavBaseManuStructure).IsOptional().HasPrecision(7,0);
            Property(x => x.MsavBaseMkt).IsOptional().HasPrecision(9,0);
        }
    }

}
// </auto-generated>
