// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class AuditDailyDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AuditDailyDetail>
    {
        public AuditDailyDetailConfiguration()
            : this("dbo")
        {
        }

        public AuditDailyDetailConfiguration(string schema)
        {
            Property(x => x.CurrRcpts).IsOptional().HasPrecision(18,2);
            Property(x => x.StatePercentage).IsOptional().HasPrecision(18,2);
            Property(x => x.Penalities).IsOptional().HasPrecision(18,2);
            Property(x => x.RefundsNsf).IsOptional().HasPrecision(18,2);
            Property(x => x.C12PercentageInterest).IsOptional().HasPrecision(18,2);
            Property(x => x.C16PercentageInterest).IsOptional().HasPrecision(18,2);
            Property(x => x.Discount).IsOptional().HasPrecision(18,2);
            Property(x => x.LossesToRoll).IsOptional().HasPrecision(18,2);
            Property(x => x.GainsToRoll).IsOptional().HasPrecision(18,2);
            Property(x => x.IsActive).IsOptional();

        }
    }

}
// </auto-generated>
