// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class CodeAreaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CodeArea>
    {
        public CodeAreaConfiguration()
            : this("dbo")
        {
        }

        public CodeAreaConfiguration(string schema)
        {
            Property(x => x.CodeArea_).IsFixedLength().IsUnicode(false);
            Property(x => x.CodeAreaDescription).IsFixedLength().IsUnicode(false);
            Property(x => x.CountyNumber).IsOptional().HasPrecision(2,0);
            Property(x => x.AsmtYear).IsOptional().HasPrecision(4,0);
            Property(x => x.MaintAreaCode).IsOptional().HasPrecision(2,0);
            Property(x => x.CodeAreaNumeric).IsOptional().HasPrecision(6,0);
            Property(x => x.StateCodeArea).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
