// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class DailyMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DailyMaster>
    {
        public DailyMasterConfiguration()
            : this("dbo")
        {
        }

        public DailyMasterConfiguration(string schema)
        {
            Property(x => x.FromDate).IsOptional();
            Property(x => x.ThruDate).IsOptional();
            Property(x => x.CheckDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.CurrencyDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.CoinDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.CashDrawerDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.RefundDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.TotalDollars).IsOptional().HasPrecision(18,2);
            Property(x => x.IsActive).IsOptional();

        }
    }

}
// </auto-generated>
