// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class DeductionHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DeductionHistory>
    {
        public DeductionHistoryConfiguration()
            : this("dbo")
        {
        }

        public DeductionHistoryConfiguration(string schema)
        {
            Property(x => x.EmployeeNumber).HasPrecision(5,0);
            Property(x => x.PaySequence).HasPrecision(1,0);
            Property(x => x.DeductionCode).IsFixedLength().IsUnicode(false);
            Property(x => x.Fund).HasPrecision(3,0);
            Property(x => x.Department).HasPrecision(3,0);
            Property(x => x.DeductionSeq).HasPrecision(1,0);
            Property(x => x.PayPeriodEndingDate).IsOptional();
            Property(x => x.Check).IsOptional().HasPrecision(5,0);
            Property(x => x.CheckType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.EmployeeAmt).IsOptional().HasPrecision(7,2);
            Property(x => x.EmployerAmt).IsOptional().HasPrecision(7,2);
            Property(x => x.EmployeeAmtPickedUp).IsOptional().HasPrecision(7,2);
            Property(x => x.Percent76).IsOptional().HasPrecision(7,6);
            Property(x => x.GrossPay).IsOptional().HasPrecision(7,2);
            Property(x => x.ExcessOvertime).IsOptional().HasPrecision(7,2);
            Property(x => x.VacationGrossWage).IsOptional().HasPrecision(7,2);
            Property(x => x.SaifHoursWorked).IsOptional().HasPrecision(4,1);
            Property(x => x.DeductSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.DirectDepositStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SaifYear).IsOptional().HasPrecision(4,0);
            Property(x => x.SaifCode).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
