// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class EmployeeMasterCommentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EmployeeMasterComment>
    {
        public EmployeeMasterCommentConfiguration()
            : this("dbo")
        {
        }

        public EmployeeMasterCommentConfiguration(string schema)
        {
            Property(x => x.EmployeeNumber).HasPrecision(5,0);
            Property(x => x.EmpMasterCommentSeq).HasPrecision(3,0);
            Property(x => x.EmpMasterCommentText).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CommentType).IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
