// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class EtAlNameConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EtAlName>
    {
        public EtAlNameConfiguration()
            : this("dbo")
        {
        }

        public EtAlNameConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.EtAlSequence).HasPrecision(2,0);
            Property(x => x.EtAlName_).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.EtAlPercentage).IsOptional().HasPrecision(7,4);
        }
    }

}
// </auto-generated>
