// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class ExemptionDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExemptionDetail>
    {
        public ExemptionDetailConfiguration()
            : this("dbo")
        {
        }

        public ExemptionDetailConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence).HasPrecision(2,0);
            Property(x => x.ExmpAmnt).IsOptional().HasPrecision(9,0);
            Property(x => x.ExemptCode).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
