// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class ExemptionMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExemptionMaster>
    {
        public ExemptionMasterConfiguration()
            : this("dbo")
        {
        }

        public ExemptionMasterConfiguration(string schema)
        {
            Property(x => x.ExemptCode).IsFixedLength().IsUnicode(false);
            Property(x => x.ExmpDesc).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ExmpAmnt).IsOptional().HasPrecision(9,0);
            Property(x => x.AsmtYear).IsOptional().HasPrecision(4,0);
            Property(x => x.PropClassCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CountyNumber).IsOptional().HasPrecision(2,0);
        }
    }

}
// </auto-generated>
