// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class FactorBookMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FactorBookMaster>
    {
        public FactorBookMasterConfiguration()
            : this("dbo")
        {
        }

        public FactorBookMasterConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.FactorBookCode).IsFixedLength().IsUnicode(false);
            Property(x => x.FactorBookDescr).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
