// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class FiscalYearBeginningBalanceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FiscalYearBeginningBalance>
    {
        public FiscalYearBeginningBalanceConfiguration()
            : this("dbo")
        {
        }

        public FiscalYearBeginningBalanceConfiguration(string schema)
        {
            Property(x => x.Year).HasPrecision(4,0);
            Property(x => x.BeginningBalance).HasPrecision(11,2);
            Property(x => x.YtdCollections).IsOptional().HasPrecision(11,2);
            Property(x => x.YtdLosses).IsOptional().HasPrecision(9,2);
            Property(x => x.YtdGains).IsOptional().HasPrecision(9,2);
            Property(x => x.YtdBalance).IsOptional().HasPrecision(14,2);

        }
    }

}
// </auto-generated>
