// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class FlaggingFullDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FlaggingFullDetail>
    {
        public FlaggingFullDetailConfiguration()
            : this("dbo")
        {
        }

        public FlaggingFullDetailConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence).HasPrecision(2,0);
            Property(x => x.FlaggingDetailYear).IsOptional().HasPrecision(4,0);
            Property(x => x.FlagComment).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.FlagStartDate).IsOptional();
            Property(x => x.FlagEndDate).IsOptional();
            Property(x => x.FlagPotentialTaxLiab).IsOptional().HasPrecision(9,2);
            Property(x => x.FlaggingCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.FlaggingMasterId).IsOptional();
            Property(x => x.FlagDescription).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
