// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class LandTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandType>
    {
        public LandTypeConfiguration()
            : this("dbo")
        {
        }

        public LandTypeConfiguration(string schema)
        {
            Property(x => x.LandType_).IsFixedLength().IsUnicode(false);
            Property(x => x.LandTypeDescr).IsFixedLength().IsUnicode(false);
            Property(x => x.LandTypeFarmNonFarm).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CountyNumber).IsOptional().HasPrecision(2,0);
            Property(x => x.TrendingTableToUse).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MsavTablesStatus).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
