// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class LandApprDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandApprDetail>
    {
        public LandApprDetailConfiguration()
            : this("dbo")
        {
        }

        public LandApprDetailConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.AppraisalDate).IsOptional();
            Property(x => x.PartOfTotl).IsOptional().HasPrecision(9,3);
            Property(x => x.ApprsrCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LandRealMktValue).IsOptional().HasPrecision(9,0);
        }
    }

}
// </auto-generated>
