// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class LandClassConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandClass>
    {
        public LandClassConfiguration()
            : this("dbo")
        {
        }

        public LandClassConfiguration(string schema)
        {
            Property(x => x.LandClassCode).IsFixedLength().IsUnicode(false);
            Property(x => x.LandClassDescription).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TrendingTableToUse).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MsavTablesStatus).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
