// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class MasterExceptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MasterException>
    {
        public MasterExceptionConfiguration()
            : this("dbo")
        {
        }

        public MasterExceptionConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.TypeException).IsFixedLength().IsUnicode(false);
            Property(x => x.ExceptionSeq).HasPrecision(3,0);
            Property(x => x.ExceptionYear).IsOptional().HasPrecision(4,0);
            Property(x => x.ExceptionEntryDate).IsOptional();
            Property(x => x.ExceptionAmountRmv).IsOptional().HasPrecision(9,0);
            Property(x => x.ExceptionAmountAv).IsOptional().HasPrecision(9,0);
            Property(x => x.FlaggingCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ExceptionComment30).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.AccruedStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.RolloverStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.YearRolledOver).IsOptional().HasPrecision(4,0);
            Property(x => x.ResetStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.NoTrendFlag).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
