// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class MobileHomeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MobileHome>
    {
        public MobileHomeConfiguration()
            : this("dbo")
        {
        }

        public MobileHomeConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Seq).HasPrecision(2,0);
            Property(x => x.XNmbr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MobileHomeId).IsOptional().HasPrecision(6,0);
            Property(x => x.YearBuilt).IsOptional().HasPrecision(4,0);
            Property(x => x.LocCostMdfr).IsOptional().HasPrecision(3,2);
            Property(x => x.MobHomeWdth).IsOptional().HasPrecision(3,0);
            Property(x => x.MobHomeLngth).IsOptional().HasPrecision(3,0);
            Property(x => x.MobHomeMnfr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MobHomeRollType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MobHomeSizeFlag).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MobHomeMrktVal).IsOptional().HasPrecision(7,0);
            Property(x => x.MhClass).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MhNmbrOfRmsLivg).IsOptional().HasPrecision(2,0);
            Property(x => x.MhNmbrOfRmsBdrm).IsOptional().HasPrecision(2,0);
            Property(x => x.MhNmbrOfRmsBath).IsOptional().HasPrecision(2,1);
            Property(x => x.MhNmbrOfRmsKtch).IsOptional().HasPrecision(2,0);
            Property(x => x.MhNmbrOfRmsDing).IsOptional().HasPrecision(2,0);
            Property(x => x.MhNmbrOfRmsUtil).IsOptional().HasPrecision(2,0);
            Property(x => x.MhNmbrOfRmsOthr).IsOptional().HasPrecision(2,0);
            Property(x => x.MhFrplcs).IsOptional().HasPrecision(2,0);
            Property(x => x.MhPhysDepr).IsOptional().HasPrecision(3,2);
            Property(x => x.FuncDepr).IsOptional().HasPrecision(3,2);
            Property(x => x.MhMiscDepr).IsOptional().HasPrecision(3,2);
            Property(x => x.QltyAdjstPct).IsOptional().HasPrecision(3,2);
            Property(x => x.AreaAdjst).IsOptional().HasPrecision(3,2);
            Property(x => x.EffctvYear).IsOptional().HasPrecision(4,0);
            Property(x => x.YearAppraised).IsOptional().HasPrecision(4,0);
            Property(x => x.BaseApprYear).IsOptional().HasPrecision(4,0);
            Property(x => x.InspctSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ApprslDate).IsOptional().HasPrecision(7,0);
            Property(x => x.AreaSqLnFeet).IsOptional().HasPrecision(5,0);
            Property(x => x.InvntrTotVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PrctGood).IsOptional().HasPrecision(3,2);
            Property(x => x.FctrBookYear).IsOptional().HasPrecision(4,0);
            Property(x => x.SpaceNumber).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Condition).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ConditionQualifier).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SeqCounter).IsOptional().HasPrecision(2,0);
            Property(x => x.CostPerUnit).IsOptional().HasPrecision(9,2);
            Property(x => x.MobHomeTipoutLngth).IsOptional().HasPrecision(3,0);
            Property(x => x.MobHomeTipoutWidth).IsOptional().HasPrecision(3,0);
            Property(x => x.SeqBinding).IsOptional().HasPrecision(3,0);
            Property(x => x.MhBaseCost).IsOptional().HasPrecision(7,0);
            Property(x => x.MhSerial).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.FctrBookCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.AcctNmbr01431).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PropClassCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ApprsrCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.HomesteadFlag).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
