// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class OwnershipHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OwnershipHistory>
    {
        public OwnershipHistoryConfiguration()
            : this("dbo")
        {
        }

        public OwnershipHistoryConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence5).HasPrecision(5,0);
            Property(x => x.OwnerName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CareOfFlag).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CareOfName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Ref).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SaleDate).IsOptional();
            Property(x => x.InstrumentCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.OwnerHstryComment).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.RefAcres).IsOptional().HasPrecision(9,3);
            Property(x => x.Jv).IsOptional().HasPrecision(7,0);
        }
    }

}
// </auto-generated>
