// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropDetail>
    {
        public PersonalPropDetailConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropDetailConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlSitusAdrs).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlDateOfOrgn).IsOptional();
            Property(x => x.PpDetlBusType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlPrrYrRtrn).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlSaleDate).IsOptional();
            Property(x => x.PpDetlNewOwnrName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlFirmName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlAsmdBusNam).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlAsmdBusAdd).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpDetlFlngSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PhoneNumber).IsOptional().HasPrecision(10,0);
            Property(x => x.ReturnFiledStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.DateReturnFiled).IsOptional();
            Property(x => x.WorkedStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ZipCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ApprsrCode).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
