// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropOtherToolConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropOtherTool>
    {
        public PersonalPropOtherToolConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropOtherToolConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence4).HasPrecision(4,0);
            Property(x => x.PpOthrBrbrSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrRdioTvSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrServGargSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrLndscSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrMedcSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrDntlSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrCnstrLogSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrOthrDesc).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpOthrToolMrktVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PpOthrNoProofMrkVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PpOthrToolPurcDate).IsOptional();
        }
    }

}
// </auto-generated>
