// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropLibraryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropLibrary>
    {
        public PersonalPropLibraryConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropLibraryConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence4).HasPrecision(4,0);
            Property(x => x.PpLibrType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpLibrSetTtle).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpLibrCmpltSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpLibrOfVlms).IsOptional().HasPrecision(5,0);
            Property(x => x.PpLibrPrchPrc).IsOptional().HasPrecision(7,0);
            Property(x => x.PpLibrMrktVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PpLibrPurcDate).IsOptional();
        }
    }

}
// </auto-generated>
