// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropFloatingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropFloating>
    {
        public PersonalPropFloatingConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropFloatingConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence4).HasPrecision(4,0);
            Property(x => x.PpFltRgstNmbr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotDatePrch).IsOptional();
            Property(x => x.PpFlotCntrctType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotCntrctOwnr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotPrchPrc).IsOptional().HasPrecision(7,0);
            Property(x => x.PpFlotMoorLocn).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotTypeOfProp).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotVsslName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpFlotMrktVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PpFlotMdlYear).IsOptional().HasPrecision(4,0);
            Property(x => x.PpFlotCond).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
