// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropNonInventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropNonInvent>
    {
        public PersonalPropNonInventConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropNonInventConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence4).HasPrecision(4,0);
            Property(x => x.PpNonGenlOffcSupp).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonMntSppl).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonOprtgSppl).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonSparPrts).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonOthrNonInvn).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonOwnrMrktVal).IsOptional().HasPrecision(7,0);
            Property(x => x.PpNonPurcDate).IsOptional();
        }
    }

}
// </auto-generated>
