// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class PersonalPropRentDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonalPropRentDetail>
    {
        public PersonalPropRentDetailConfiguration()
            : this("dbo")
        {
        }

        public PersonalPropRentDetailConfiguration(string schema)
        {
            Property(x => x.AsmtYear).HasPrecision(4,0);
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.Sequence5).HasPrecision(5,0);
            Property(x => x.PpRentId).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpRentModlYear).IsOptional().HasPrecision(4,0);
            Property(x => x.PpRentFilrSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpRentPayrSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpRentAnnlLeas).IsOptional().HasPrecision(7,0);
            Property(x => x.PpRentDate).IsOptional();
            Property(x => x.PpRentAgrmntLgth).IsOptional().HasPrecision(2,0);
            Property(x => x.PpOrigCost).IsOptional().HasPrecision(7,0);
            Property(x => x.PpRentQnty).IsOptional().HasPrecision(4,0);
            Property(x => x.PpRentItemMrktValue).IsOptional().HasPrecision(7,0);
            Property(x => x.DrcFlag).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.PpCategoryCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SecondPartyAcctAcctNmb).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
