// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class SalesFullDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesFullDetail>
    {
        public SalesFullDetailConfiguration()
            : this("dbo")
        {
        }

        public SalesFullDetailConfiguration(string schema)
        {
            Property(x => x.SaleIdentification).IsFixedLength().IsUnicode(false);
            Property(x => x.AcctNmbr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CommentsExistStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SaleDate).IsOptional();
            Property(x => x.BuyerName).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.NetSalesPrice).IsOptional().HasPrecision(9,0);
            Property(x => x.ConditionCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SaleRatio).IsOptional().HasPrecision(5,2);
            Property(x => x.MultiAccountFlag).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
