// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class SalesAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesAccount>
    {
        public SalesAccountConfiguration()
            : this("dbo")
        {
        }

        public SalesAccountConfiguration(string schema)
        {
            Property(x => x.SaleIdentification).IsFixedLength().IsUnicode(false);
            Property(x => x.AcctNmbr).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.AcctLandAssessedTotal).IsOptional().HasPrecision(9,0);
            Property(x => x.AcctImprovementTotal).IsOptional().HasPrecision(9,0);
            Property(x => x.SalesAcres).IsOptional().HasPrecision(9,3);
            Property(x => x.PrimeIndicator).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.MultiAccountSaleStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CommentsExistStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.AcctMobileHomeTotal).IsOptional().HasPrecision(7,0);
            Property(x => x.Twnshp).IsOptional().HasPrecision(2,0);
            Property(x => x.TwnshpDir).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Range).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.RangDir).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Sctn).IsOptional().HasPrecision(2,0);
            Property(x => x.QtrSctn).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Prcl).IsOptional().HasPrecision(5,0);
            Property(x => x.SpecIntAlph).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.SpecIntNmbr).IsOptional().HasPrecision(2,0);
            Property(x => x.PrimeIndicatorNonDisp).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
