// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class TaxFeeFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TaxFeeFile>
    {
        public TaxFeeFileConfiguration()
            : this("dbo")
        {
        }

        public TaxFeeFileConfiguration(string schema)
        {
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.TaxRollYear).HasPrecision(4,0);
            Property(x => x.PayFeeType).IsFixedLength().IsUnicode(false);
            Property(x => x.TaxFeeSeq).HasPrecision(3,0);
            Property(x => x.TaxFeeWarNum).IsOptional().HasPrecision(8,0);
            Property(x => x.TaxFeeAmt).IsOptional().HasPrecision(7,2);
            Property(x => x.TaxFeeIssueDate).IsOptional().HasPrecision(7,0);
            Property(x => x.TaxFeeDocDate).IsOptional().HasPrecision(7,0);
            Property(x => x.TaxFeeReleaseDate).IsOptional().HasPrecision(7,0);
        }
    }

}
// </auto-generated>
