// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class TaxLenderFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TaxLenderFile>
    {
        public TaxLenderFileConfiguration()
            : this("dbo")
        {
        }

        public TaxLenderFileConfiguration(string schema)
        {
            Property(x => x.LenderNumber).IsFixedLength().IsUnicode(false);
            Property(x => x.LenderSeqNumber).HasPrecision(3,0);
            Property(x => x.LenderDescription).IsFixedLength().IsUnicode(false);
            Property(x => x.LenderAddress).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LenderAddress2).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.ZipCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LenderRep).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LenderAreaCode).IsOptional().HasPrecision(3,0);
            Property(x => x.LenderPhone).IsOptional().HasPrecision(7,0);
            Property(x => x.LenderType).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LenderPrintStatus).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
