// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class TaxMasterMaintFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TaxMasterMaintFile>
    {
        public TaxMasterMaintFileConfiguration()
            : this("dbo")
        {
        }

        public TaxMasterMaintFileConfiguration(string schema)
        {
            Property(x => x.AcctNmbr).IsFixedLength().IsUnicode(false);
            Property(x => x.LenderNumber).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.LenderSeqNumber).IsOptional().HasPrecision(3,0);
            Property(x => x.TaxMstrLoanInfo).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrTapeExchg).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrTaxStatus).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrPaymentPlan).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrFclsDate).IsOptional();
            Property(x => x.TaxMstrJndDate).IsOptional();
            Property(x => x.TaxMstrFclsList).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrJndCase).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.TaxMstrPullNumber).IsOptional().HasPrecision(5,0);
            Property(x => x.BankruptcyCode).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.BankruptcyCourtFileDte).IsOptional();
            Property(x => x.BankruptcyCourtLastAcc).IsOptional();
            Property(x => x.BankruptcyOpenCaseSts).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.BankruptcyCaseNumber).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.BankruptcyClaimFileDte).IsOptional();
            Property(x => x.BankruptcyPlnConfirmDt).IsOptional();
            Property(x => x.BankruptcyDischargeDate).IsOptional();
            Property(x => x.BankruptcyCaseCloseDte).IsOptional();
            Property(x => x.BankruptcyLastActDate).IsOptional();
            Property(x => x.AttorneyTrusteeSeq).IsOptional().HasPrecision(5,0);
            Property(x => x.TrusteeAttorneyTrustee).IsOptional().HasPrecision(5,0);
            Property(x => x.PostPetitionYear).IsOptional().HasPrecision(4,0);
            Property(x => x.RedemptionFeeAmount).IsOptional().HasPrecision(6,2);
        }
    }

}
// </auto-generated>
