// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class ValueAreaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ValueArea>
    {
        public ValueAreaConfiguration()
            : this("dbo")
        {
        }

        public ValueAreaConfiguration(string schema)
        {
            Property(x => x.ValAreaCode).IsFixedLength().IsUnicode(false);
            Property(x => x.ValAreaDesc).IsFixedLength().IsUnicode(false);
            Property(x => x.FrmNonFrmFlag).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.CountyNumber).IsOptional().HasPrecision(2,0);
            Property(x => x.LocCostMdfr).IsOptional().HasPrecision(3,2);
        }
    }

}
// </auto-generated>
