// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HarneyCounty.Infrastructure.Core.Mappings
{
    using HarneyCounty.Domain.Core.Models;

    public class ZipCodeFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ZipCodeFile>
    {
        public ZipCodeFileConfiguration()
            : this("dbo")
        {
        }

        public ZipCodeFileConfiguration(string schema)
        {
            Property(x => x.ZipCode).IsFixedLength().IsUnicode(false);
            Property(x => x.City).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.State).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.Country).IsOptional().IsFixedLength().IsUnicode(false);
        }
    }

}
// </auto-generated>
